### ISSUE TITLE
Add graphs templates

### ISSUE THREAD

**Issue by falzm** [facette/facette#112]
Implement a templating system to allow dynamic graphs rendering.

The idea is to be able to display collections featuring graphs based on a pre-defined "model", but without requiring explicitly defined graphs features such as sources and metrics.

**Comment by vbatoufflet** [comment]
Graphs templates are in the process of being shipped soon and we are working on collection template support.

See [facette:templates](https://github.com/facette/facette/tree/templates) for details.

**Comment by falzm** [comment]
A dedicated issue (#170) has been opened for collection templates implementation, since it will be released in a separate version.
