### ISSUE TITLE
Color picker should be neatly integrated

### ISSUE THREAD

**Issue by Zopieux** [facette/facette#124]
When choosing a serie's color, a first popup is displayed in which user can reset or pick then save. Picking a color currently makes a second dialog to pop (the color palette itself) in a theme that does not respect facette main theme.

I suggest embedding the color palette directly into the color pick dialog so this is both simpler, quicker and neater.

**Comment by vbatoufflet** [comment]
This will be handled with the new UI being developed.

**Comment by vbatoufflet** [comment]
See #264
