### ISSUE TITLE
Pages can't be scrolled via keyboard

### ISSUE THREAD

**Issue by twm** [facette/facette#141]
Many parts of the Facette UI can't be scrolled via keyboard unless you focus the content are by clicking it first.  The layout should probably leave the scrolling alone and use `position: fixed` to keep things visible.

This problem also affects the docs on facette.io. 

Tested in Chrome 38 and Firefox 33 on Ubuntu 12.04.

**Comment by vbatoufflet** [comment]
Hi @twm,

Just for letting you know and as it has been a while since you opened this issue.

This has been addressed in the process of rebuilding a fully new UI that should come with one of the next releases when all the remaining work on this UI will be completed :smiley:

**Comment by falzm** [comment]
Fixed in branch [0.4-alpha](https://github.com/facette/facette/tree/0.4-alpha).
