### ISSUE TITLE
'where' and 'group by' filters

### ISSUE THREAD

**Issue by cnf** [facette/facette#152]
cadvisor logs all its data to the same series in influxdb. the differentiator is the container_name field

In grafana, I can set a `where container_name ~ <some name>` or `group by container_name` so that the data gets applied to the correct entry.

something like this is needed for facette as well, if the influxdb provider is to be of any use.

**Comment by vbatoufflet** [comment]
Starting with the > 0.4.0, the InfluxDB connector can handling mapping (see https://docs.facette.io/latest/api/providers/#influxdb) to ensure which columns should be used as source or metric.
