### ISSUE TITLE
UI-less Graphs and collections creation

### ISSUE THREAD

**Issue by jawher** [facette/facette#155]
Hi !

I was playing with Facette and I'm loving what I've seen so far.

Maybe I missed something, but I don't think that graphs and collections can be created and configured in an automatable way, i.e in user-written json files in a known location (`/etc/facette/graphs` for example) with something like ansible for example.  
You have to go through the web UI instead.

I played bit with manually creating json files under `/var/lib/facette/graphs/...`, but that confused facette to no end afterwards, so I don't think users are supposed to touch that.

**Comment by vbatoufflet** [comment]
Hi,

The only other “official” way to create items in Facette's library not using the web UI is to use the REST API, documented here: http://docs.facette.io/api/library/ .

Indeed, directly writing in `/var/lib/facette` is not recommended as we are in the process of changing the storage backend for something like a SQL based one.

**Comment by jawher** [comment]
Thanks for the prompt reply !

> The only other “official” way to create items in Facette's library not using the web UI is to use the REST API, documented here: http://docs.facette.io/api/library/.

Indeed, you can use the REST api to create graphs and collections.

The thing is: REST, while developer and tooling friendly, is not very friendly to configuration management tools like ansible.  
In my case, my goal is to automate the setup of a host with a website, collected and facette for monitoring.  
I could use the uri core module to call the REST api. The problem is that if the playbook is replayed (due to a failure somewhere), the POST requests are not idempotent and replaying them might (will ?) create duplicate objects.

A file based system in the other hand is more bullet proof: just copy the definition files in a known location and (re)start facette for them to be picked up.

Anyway, that's my personal view on things. I'm sure you guys have spent more time thinking about it and have a clear idea on where to go with the product.

It's just that what made me pick up facette its deployment simplicity: a static binary which doesn't need a Ruby or PHP runtime for example nor a database to be installed and configured.

**Comment by vbatoufflet** [comment]
Indeed storing data as json files on the filesystem seemed the easiest way to prevent a huge database dependency at the time.

The problem we encounter with this approach is to maintain a certain level of consistency across various items in Facette's library. So we thinking of a SQL based storage using SQLite (and figure a way to support alternate drivers like PostgreSQL and MySQL).

Regarding a way to insert data without duplicating items, you can always use `PUT` requests with an arbitrary _uuid_ (see [Update an existing graph](http://docs.facette.io/api/library/#toc_26)).
