### ISSUE TITLE
Add a "title" property to graphs

### ISSUE THREAD

**Issue by falzm** [facette/facette#157]
In order to implement graph/collection templates, we must be able to "templatify" a graph/collection's title. Currently the `name` property of these objects is used as title, but the back-end requires that this property remains unique among all objects of a same type.

The solution discussed is to add a new `title` property that will be used only for display purposes, and that can contain templating tags.

**Comment by vbatoufflet** [comment]
Shipped in the template branch (see 193fb4b14728a7f87d7e563755fb92b53bb3ab23).
