### ISSUE TITLE
Time period for a collection

### ISSUE THREAD

**Issue by gy0kuro** [facette/facette#158]
For a given collection we can restrict the display with time cursors (1y, 1m, 7d, 3d, etc.) on a single graph at a time. It would be nice to add a feature to limit the entire 'collection' (x graphs) in one pass : the resulting view is then used to correlate to a given period of time.

**Comment by vbatoufflet** [comment]
Hi Thomas,

Is the feature wanted, something like a global button on top of a collection being a shortcut to choosing a time range on a graph then clicking on “Propagate Time Range”?

**Comment by gy0kuro** [comment]
Hi Vincent,

Yep, something like this. For the position, at the same level of 'print / edit' buttons (in orange on the screenshot) :
![facette](https://cloud.githubusercontent.com/assets/11042104/6226376/cc7ee4da-b694-11e4-92df-b09e0d3acb66.png)

Not sure for the two pass, the button 'Modify Time Range' on graphs is perfect (AMHA).

Nice job anyway for this Web UI : easy to deploy / configure, well documented and eye candy.

**Comment by vbatoufflet** [comment]
Thanks.

We can certainly manage to add this :smile:

**Comment by gy0kuro** [comment]
Kewl :)

**Comment by max-zelinski** [comment]
eagerly waiting for this feature :)

**Comment by vbatoufflet** [comment]
This has been shipped in 1635805148f10d04cb2bfbf37b14155a946aa69e.
