### ISSUE TITLE
Where is the colour picker?

### ISSUE THREAD

**Issue by TomGudman** [facette/facette#177]
Hi,

Sorry for the noise, I am bit ashamed to ask this question but I am unavailable to find how to change the color for a metric (serie). Can you tell me how to do it and/or where I should look at? I am using 0.4.0-dev (81fd3f8). At the same time if someone - as a bonus question - what's the purpose of 'autoname series'. 

I read to try to figure out: 
- https://github.com/facette/facette/issues/124
- https://blog.facette.io/2014/07/31/facette-101/ (too old I guess)

Thank you and "Desole"
Thomas

**Comment by vbatoufflet** [comment]
Hi Thomas,

There is nothing to be ashamed of. We implemented the feature so naturally it seemed obvious to us. But I can understand that someone who never used it might not get it.

Please see the screenshot below:

![facette-admin_colorpicker](https://cloud.githubusercontent.com/assets/598433/6841447/13580ad6-d38b-11e4-8f22-5c4d0d0fde10.png)

Regarding series' auto-naming, it was designed as an helper to get all selected series having a unique name and it basically works like this:

 * by default series name contains only the metric name: `cpu.0.idle`
 * when the same metric is added multiple times for the same source, they are suffixed: `cpu.0.idle (n)` where `n` is an incremented counter
 * if the same metric is added for different sources, those sources are used as prefixes: `source1/cpu.0.idle` and `source2/cpu.0.idle`, the same goes for origins

Auto-naming if used by default when appending metrics to a graph. The button you mention in the UI serves to force series renaming, when their names have already been modified in the next creation steps or when you edit a graph afterwards.

Hope it helps.

Vincent

**Comment by TomGudman** [comment]
Hi Vincent,

Thanks for the quick reply. It's all crystal clear now.

I have to say the colour picker is well hidden, I think I would have 
never found it. I kept looking on the right hand side of the series...

I reckon a doco update for that would be good. Hopefully noobs like me 
will find this github issues to help them ;)

Thanks again, you can resolve the issue (if I can't ;-)

Otherwise, facette is great I kept an eye on it for more than a year and 
I finally found the time to use it. When I have the time I will see if I 
can build a RPM spec.

Cheers,
Thomas

**Comment by TomGudman** [comment]
Resolving. Questions have been answered.
