### ISSUE TITLE
Embedded UI files

### ISSUE THREAD

**Issue by falzm** [facette/facette#178]
In order to use the deployment of Facette, I suggest embedding a copy of the web UI files in the backend binary to provide a self-contained instance.

If the users want to customize the UI, the backend could use the user-specified `base_dir` configuration setting and use external files to render the UI.

WDYT?

**Comment by vbatoufflet** [comment]
Maybe we can ship embeddable version in specific builds yes, it could be useful. Then, keeping the current builds at their state.

**Comment by falzm** [comment]
The point actually is to not have different builds: started with `base_dir` setting value the backend would use embedded UI files, otherwise it would use external files.

**Comment by vbatoufflet** [comment]
Shipped in [0.4-alpha](https://github.com/facette/facette/tree/0.4-alpha) via a dedicated `builtin_assets` build tag.
