### ISSUE TITLE
Support wildcards when adding metrics

### ISSUE THREAD

**Issue by martinp** [facette/facette#181]
Adding multiple metrics is a bit cumbersome. Especially for the CPU metric from collectd, which collects a metric per state per CPU/core.

I think being able to use wildcards would help a lot. It would also make templates easier to reuse, e.g. `cpu.*.*` would work for hosts that have a varying number of CPUs/cores.

**Comment by falzm** [comment]
Hi Martin

I suggest you to use *metric groups*: you declare your group of metrics (you can use glob-like patterns), then use this metric group in your series instead of cherry-picking each metric.

**Comment by martinp** [comment]
Didn't know about metric groups, but they seem to do exactly what I want, even regular expressions. Thanks!

**Comment by falzm** [comment]
You're welcome :)
