### ISSUE TITLE
Last is always null

### ISSUE THREAD

**Issue by martinp** [facette/facette#182]
When graphing metrics from collectd the displayed `last` value is always `null`. Not sure if this is expected behaviour when using collectd.

I'm using 0.3.0rc1.

**Comment by psytra** [comment]
sorry for the noise, I accidentally created a PR in my own fork..
now, everything should be nice.

**Comment by vbatoufflet** [comment]
Fixed in e1e0353f3bddb26d51a3cee3eea374ba30720b3c.
