### ISSUE TITLE
Add graph units and scale automatically using provider/connector config

### ISSUE THREAD

**Issue by psytra** [facette/facette#187]
Idea of @vbatoufflet in #176: 
Indeed, I understand that having to fill units every time when you create graphs could be a little bit repetitive.

I guess we can implement some metrics defaults in providers configuration files as for filters using patterns and setting default values for units and/or scales. Then, leaving a possibility to override them in the UI when creating a graph.

For example:

```
…
"metrics_defaults": [
    { "pattern": "net\..+\.octets", "unit": "bits", "scale": 0.125 }
]
```

I'd prefer having the config based on origins and not on connectors (if that terminology is correct), so configure the metrics for myrrd rather than generic rrd.

**Comment by vbatoufflet** [comment]
Scales and units have been removed from Facette 0.4.
