### ISSUE TITLE
UI quirk - Graph height

### ISSUE THREAD

**Issue by jerryjacobs** [facette/facette#188]
When you:
- Toggle legend
  - Legend is displayed
- Reset time range
  - Legend is gone

Then the graph is same height as previous height + height of shown legend.

Hope this is clear enough to reproduce :-)

**Comment by psytra** [comment]
I also discovered that ~~bug~~ feature.. 
There should be a possibility to change the height of graphs. I'm not aware that there is such a thing already.

**Comment by vbatoufflet** [comment]
That is definitively not an intended behavior :wink:

Regarding the possibility to to set graphs height, it is not possible at the time, but it could be added in the future for sure.

**Comment by psytra** [comment]
I have fixed the issue in my local copy. I also added height adjustment buttons, there.
I guess I'll be able to prepare the PRs in the next days...

**Comment by jerryjacobs** [comment]
Awesome :+1:

**Comment by psytra** [comment]
Don't know if the notifications work when commits are referenced.. So.. Here they are.. feel free to test..

**Comment by jerryjacobs** [comment]
It seemed I received no email notify when referenced is added.

**Comment by vbatoufflet** [comment]
Hi Matthias,

Thank you for this PR. I will review it and let you know.
