### ISSUE TITLE
Colour dots in tooltip/legend should be symbols 

### ISSUE THREAD

**Issue by psytra** [facette/facette#189]
Right now, multiple series with the same colour cannot directly be easily mapped to the plotted lines.
Thus the coloured dots should be substituted by the highchart symbols.

**Comment by vbatoufflet** [comment]
I will see what can be done to perform this change.

**Comment by falzm** [comment]
Agreed.

**Comment by psytra** [comment]
I've got this one.. 

![facette-icons](https://cloud.githubusercontent.com/assets/1681739/7437093/a77bec9c-f054-11e4-964a-d0a7dd01df01.png)

let me know if you'd like to have a PR..

Right now, there is a bug that symbols are not selected correctly. I have no clue why all pink series use dots as symbols.. Don't know if it is a highcharts problem.

**Comment by vbatoufflet** [comment]
Hi Matthias,

This is great. If you want to open a PR for this issue it will be nice.

Though, are the drop shadows an intended style in legend?

**Comment by psytra** [comment]
Shadow was a relict as I tried to place the symbols in the existing rectangle.. It is now flat. 

![facette-icons](https://cloud.githubusercontent.com/assets/1681739/7442643/cb08aeb4-f119-11e4-9968-8bab9ada02fa.png)

**Comment by vbatoufflet** [comment]
The #201 has been merged. Thanks again for your help on this matter.
