### ISSUE TITLE
UI quick - Unable to determine version/build in webinterface

### ISSUE THREAD

**Issue by jerryjacobs** [facette/facette#190]
Most webapps display their version/build in the footer or admin panel to determine the running version. It would be nice to have a "info/about" window in setting and/or a version/build on the frontpage somewhere.

Just an idea.

**Comment by falzm** [comment]
Hi Jerry

You're right, this is a good idea: I opened the issue #194 regarding this issue.

Thank you for your feedback.

**Comment by jerryjacobs** [comment]
Thanks for picking this up, this issue can be closed then. and will proceed in #194
