### ISSUE TITLE
Display version in the UI

### ISSUE THREAD

**Issue by falzm** [facette/facette#194]
As discussed in #190, we should display the software version somewhere in the UI – I suggest in the admin panel home page.

**Comment by jerryjacobs** [comment]
Software version MAY contain the following items:
* Version
* Commit hash
* Build date
* Used compiler/toolchain version

**Comment by vbatoufflet** [comment]
Shipped in 8bf334ab0b3d6422e76d9d94c9a5385fdf3a9ec1.

**Comment by vbatoufflet** [comment]
Build details have been added onto the Admin Panel landing page:
![screen shot 2015-05-02 at 16 41 49](https://cloud.githubusercontent.com/assets/598433/7441481/35a0ccb4-f0ea-11e4-815f-af6afc28f461.png)

**Comment by jerryjacobs** [comment]
Awesome :-)!

**Comment by xor-gate** [comment]
I tried to add "hide_build_details" : false  to the configuration file but is displayed with the release 0.3.0.

**Comment by vbatoufflet** [comment]
I tried to switch from `false` to `true` and vice versa on the demo instance and it seems to work properly.

You are using the same version as the one on http://demo.facette.io/admin/ ?

```
Version: 0.3.0
Build Date: 2015-07-08
Compiler: gc (go1.4.2)
```

Can you share your configuration with us?

**Comment by xor-gate** [comment]
**I have it working myself, when gathering together my hand installed setup I figured out the base_dir was pointing to a folder which had not the updated template folder. Thanks for you time.**

I'm running facette under SystemD and created my own Unit file

**/etc/systemd/system/facette.service**

```
[Unit]
Description=Facette

[Service]
User=facette
ExecStart=/opt/facette/facette-linux-amd64/bin/facette

[Install]
WantedBy=multi-user.target
```

**/opt/facette/facette-linux-amd64/bin/facette -V**

```
facette version 0.3.0, built on 2015-07-08
Go version: go1.3.3 (gc)

Available connectors:
   facette
   graphite
   influxdb
   kairosdb
   rrd
```

**/etc/facette/facette.json**

```
{
	"bind": ":12003",
	"base_dir": "/usr/local/share/facette",
	"providers_dir": "/etc/facette/providers",
	"data_dir": "/tmp/facette",
	"pid_file": "/tmp/facette.pid",
	"read_only": false,
	"hide_build_details" : false
}
```
