### ISSUE TITLE
Management API

### ISSUE THREAD

**Issue by falzm** [facette/facette#199]
In order to perform administrative tasks on a Facette instance, implement a dedicated management API. Access to this API should be restricted by default, as it will be possible to modify/delete library data – e.g. backup restoring – on a Facette instance.

**Comment by jerryjacobs** [comment]
Suggestion for a management protocol could be JSON-RPC 2.0 this is already a well stable and documented protocol.

**Comment by vbatoufflet** [comment]
No longer relevant due to [0.4-alpha](https://github.com/facette/facette/tree/0.4-alpha) changes.
