### ISSUE TITLE
Support for InfluxDB 0.9.x

### ISSUE THREAD

**Issue by mnuessler** [facette/facette#202]
Just a question, is InfluxDB 0.9 already supported? The HTTP API has changed significantly in 0.9.

**Comment by falzm** [comment]
Hi Matthias,

We haven't implemented compatibility with InfluxDB 0.9.x yet, we'll do it once this branch is released as stable.

**Comment by mnuessler** [comment]
Hi Marc, thanks for the info. Looking forward to have support for InfluxDB 0.9.x in facette. Btw, InfluxDB 0.9.0 will probably be released soon. Maybe it is worth thinking about how to support 0.8 and 0.9 in parallel? Or are you planning to drop support for 0.8 once 0.9 has been released?

**Comment by falzm** [comment]
Matthias

At the moment we haven't decided whether we'll support both 0.8.x and 0.9.x – my first guess would be to do so, since it's been a long time between 0.8.x and 0.9.x branches and many people would have deployed InfluxDB in the mean time, so there might be a significant user base for 0.8.x.

Cheers

**Comment by mnuessler** [comment]
FYI: [Grafana](http://grafana.org/features/) already supports InfluxDB 0.9 as a datasource (as well as InfluxDB 0.8).

**Comment by mnuessler** [comment]
FYI: InfluxDB 0.9.0 has just been [released today](http://influxdb.com/blog/2015/06/11/InfluxDB-v0_9_0-released-with-developer-and-production-support.html).

**Comment by vbatoufflet** [comment]
Hi Matthias,

We plan to implement the new support soon. But as the API and the client library changed, we will need to figure a proper way to offer access to both 0.8 and 0.9.

We will let you know ass soon as it will be available.

**Comment by vbatoufflet** [comment]
A new connector for InfluxDB 0.9 is on its way, see [influxdb-0.9](https://github.com/facette/facette/tree/influxdb-0.9).

The old connector has been renamed to `influxdb_legacy`.

**Comment by vbatoufflet** [comment]
Were are currently waiting for a upstream issue to be fixed:

https://github.com/influxdb/influxdb/issues/3326

We will update this issue when we will be able to finalize its support.

**Comment by mparienti** [comment]
This issue has been closed in the 0.9.3 release of InfluxDB :-)
