### ISSUE TITLE
Facette crash due to new rrdtool 1.5.3

### ISSUE THREAD

**Issue by jerryjacobs** [facette/facette#207]
Hi all,

I tried to add a collectd plugin in python/perl which monitors Transmission Bittorrent downloader. This works and it generated rrd graphs. Now when I start facette and try to navigate into a already created collection Facette completly crashes on the 3th party rrd golang library.

Still when the rrd graphs are "crap", it should NOT crash facette IMHO.

Collectd perl transmission plugin I tried: https://github.com/ioanrogers/Collectd-Plugins-Transmission
Collectd python transmission plugin I tried: 
https://gist.github.com/salmonmoose/1c570d99bc6508e6fa73
or 
https://github.com/akosiaris/collectd_transmission

Go Trace:
```
May 14 10:01:28 misc001 systemd[1]: Starting Facette...
May 14 10:01:33 misc001 facette[21784]: fatal error: unexpected signal during runtime execution
May 14 10:01:33 misc001 systemd[1]: facette.service: main process exited, code=exited, status=2/INVALIDARGUMENT
May 14 10:01:33 misc001 systemd[1]: Unit facette.service entered failed state.
May 14 10:01:33 misc001 systemd[1]: facette.service failed.
May 14 10:02:37 misc001 systemd[1]: Started Facette.
May 14 10:02:37 misc001 systemd[1]: Starting Facette...
May 14 10:02:42 misc001 facette[22178]: fatal error: unexpected signal during runtime execution
May 14 10:02:42 misc001 facette[22178]: [signal 0xb code=0x1 addr=0x0 pc=0x7fa4acf2d7e6]
May 14 10:02:42 misc001 facette[22178]: runtime stack:
May 14 10:02:42 misc001 facette[22178]: runtime.gothrow(0x9126d0, 0x2a)
May 14 10:02:42 misc001 facette[22178]: /usr/local/go/src/runtime/panic.go:503 +0x8e
May 14 10:02:42 misc001 facette[22178]: runtime.sigpanic()
May 14 10:02:42 misc001 facette[22178]: /usr/local/go/src/runtime/sigpanic_unix.go:14 +0x5e
May 14 10:02:42 misc001 facette[22178]: goroutine 660 [syscall, locked to thread]:
May 14 10:02:42 misc001 facette[22178]: runtime.cgocall_errno(0x401ad0, 0xc2086d3120, 0x0)
May 14 10:02:42 misc001 facette[22178]: /usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc2086d3100 sp=0xc2086d30d8
May 14 10:02:42 misc001 facette[22178]: github.com/facette/facette/thirdparty/github.com/ziutek/rrd._Cfunc_rrdXport(0xc2086d3178, 0xe0000000d, 0xc2085d7ce0, 0xc2086d317c, 0xc2086d31a8, 0xc2086d31b0, 0xc2086d31a0, 0xc2086d31b8, 0xc2086d31c8, 0xc2086d31d0, ...)
May 14 10:02:42 misc001 facette[22178]: /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/thirdparty/github.com/ziutek/rrd/:84 +0x44 fp=0xc2086d3120 sp=0xc2086d3100
May 14 10:02:43 misc001 systemd[1]: facette.service: main process exited, code=exited, status=2/INVALIDARGUMENT
May 14 10:02:43 misc001 systemd[1]: Unit facette.service entered failed state.
May 14 10:02:43 misc001 systemd[1]: facette.service failed.
```

Eventually I could provide the rrd graphs which causes the crash so you don't have to install collectd, python and all other dependencies.

**Comment by jerryjacobs** [comment]
I do get a little more output, seems the python and perl module produce (possible) different crashes:
```
May 14 09:45:03 misc001 systemd[1]: Starting Facette...
May 14 09:45:12 misc001 facette[19445]: fatal error: unexpected signal during runtime execution
May 14 09:45:12 misc001 facette[19445]: [signal 0xb code=0x1 addr=0x0 pc=0x7efdb8e477e6]
May 14 09:45:12 misc001 facette[19445]: runtime stack:
May 14 09:45:12 misc001 facette[19445]: runtime.gothrow(0x9126d0, 0x2a)
May 14 09:45:12 misc001 facette[19445]: /usr/local/go/src/runtime/panic.go:503 +0x8e
May 14 09:45:12 misc001 facette[19445]: runtime.sigpanic()
May 14 09:45:12 misc001 facette[19445]: /usr/local/go/src/runtime/sigpanic_unix.go:14 +0x5e
May 14 09:45:12 misc001 facette[19445]: goroutine 664 [syscall, locked to thread]:
May 14 09:45:12 misc001 facette[19445]: runtime.cgocall_errno(0x401ad0, 0xc20873b120, 0x0)
May 14 09:45:12 misc001 facette[19445]: /usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc20873b100 sp=0xc20873b0d8
May 14 09:45:12 misc001 facette[19445]: github.com/facette/facette/thirdparty/github.com/ziutek/rrd._Cfunc_rrdXport(0xc20873b178, 0xe0000000d, 0xc2080b7730, 0xc20873b17c, 0xc20873b1a8, 0xc20873b1b0, 0xc20873b1a0, 0xc20873b1b8, 0xc20873b1c8, 0xc20873b1d0, ...)
May 14 09:45:12 misc001 facette[19445]: /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/thirdparty/github.com/ziutek/rrd/:84 +0x44 fp=0xc20873b120 sp=0xc20873b100
May 14 09:45:12 misc001 facette[19445]: github.com/facette/facette/thirdparty/github.com/ziutek/rrd.(*Exporter).xport(0xc2080ba3c0, 0xecce63b78, 0x34b8641f, 0xcad0e0, 0xecce64988, 0xc234b8641f, 0xcad0e0, 0x2540be400, 0x0, 0x0, ...)
May 14 09:45:12 misc001 facette[19445]: /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/thirdparty/github.com/ziutek/rrd/rrd_c.go:489 +0x2ec fp=0xc20873b2e8 sp=0xc20873b120
May 14 09:45:12 misc001 facette[19445]: github.com/facette/facette/thirdparty/github.com/ziutek/rrd.(*Exporter).Xport(0xc2080ba3c0, 0xecce63b78, 0xc234b8641f, 0xcad0e0, 0xecce64988, 0x34b8641f, 0xcad0e0, 0x2540be400, 0x0, 0x0, ...)
May 14 09:45:12 misc001 facette[19445]: /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/thirdparty/github.com/ziutek/rrd/rrd.go:450 +0xb4 fp=0xc20873b420 sp=0xc20873b2e8
May 14 09:45:12 misc001 systemd[1]: facette.service: main process exited, code=exited, status=2/INVALIDARGUMENT
May 14 09:45:12 misc001 systemd[1]: Unit facette.service entered failed state.
```

**Comment by vbatoufflet** [comment]
Hi Jerry,

Thanks for reporting this. You are right, faulty RRD files should definitively not crash Facette :wink: 

Indeed, it would be great if you could provide us with a `.rrd` file making Facette panic (e.g. sending it to dev@facette.io or our addresses listed in the `AUTHORS` file).

**Comment by jerryjacobs** [comment]
I added them to my fork here: https://github.com/jerryjacobs/facette/tree/rrd-crashfiles

**Comment by vbatoufflet** [comment]
Sure :smile: 

Thanks for the files. We will take a look at it.

**Comment by jerryjacobs** [comment]
Awesome

**Comment by vbatoufflet** [comment]
Hi Jerry,

I tried to reproduce the crash, but even with the provided `.rrd` files I didn't succeed.

Can you please, if possible, provided us with the graph definition data (using `curl -s http://<facette_instance>/api/v1/library/graphs/<graph_id>` for example)?

**Comment by jerryjacobs** [comment]
Hi Vincent,

I tried to reproduce the crash under different circumstances, because facette is normaly running behind a NGINX SSL terminated proxy:

* Access facette direct instead at NGNIX https frontend proxy
* Clear facette cache
* Try to add just the collectd cpu.0.idle

There seems something more wrong here at my side possibly, because when I clear the facette cache and use the normal collectd cpu.0.idle metric then it still crashes on the rrd 3th party golang library. I'm running ArchLinux 64 bit, and i'm not sure if a system upgrade did break something.

If I look at the changes of ArchLinux repository, the rrdtool upgraded 8 days ago from version 1.4.9-1 to 1.5.3-1. Maybe this could be the case. If you look at debian they still "stuck" on version 1.4.7 (stable) or 1.4.8 (experimental). 

https://projects.archlinux.org/svntogit/packages.git/log/trunk?h=packages/rrdtool
https://packages.debian.org/search?keywords=rrdtool&searchon=names&suite=all&section=all

**Conclusion**

Happily the pacman package manager caches the old packages, I downgraded rrdtool back to rrdtool-1.4.9-1 and everything seems to back to normal even with the plugin generated graphs!

**Recommendation**

I think the 3th party rrd library needs to be tested against rrdtool 1.5.3.

End of issue :-)

**Comment by vbatoufflet** [comment]
Ok, thanks for the investigation. It's always good to know.

**Comment by jerryjacobs** [comment]
Proposed upstream support for rrdtool 1.5.x: https://github.com/facette/facette/issues/207

**Comment by xor-gate** [comment]
Seems debian unstable now uses rrdtool 1.5.x, notified 3thparty implementation used by facette here: https://github.com/ziutek/rrd/issues/24

**Comment by xor-gate** [comment]
@vbatoufflet it seems the upstream author has tested it on debian with librrd4 (1.5) and seems to work. Could you put this in the nightly to check if it is working or is it to much hassle?

**Comment by vbatoufflet** [comment]
Hi Jerry,

I will take a look at it.
