### ISSUE TITLE
Impossible to clone instance of graph template

### ISSUE THREAD

**Issue by i0oi** [facette/facette#208]
I can't clone an instance of graph template

For reproduce : 
- Create a graph template
- Create an instance of this template
- Clone this instance

I have the message "Resource is invalid" but no log.

Environment :
OS : 
- Debian Jessie with facette version 0.4.0dev, built on 2015-05-18 [Go version: go1.3.3 (gc)]
- Debian Wheezy with facette version 0.3.0rc1 [Go version: go1.4.2 (gc)]

**Comment by i0oi** [comment]
Additional information : 
- The bug is present if graph template have description.

**Comment by vbatoufflet** [comment]
Fixed in 3ff0fca01abbdcc0319c97b3df4a9731d5d05cd7.
