### ISSUE TITLE
Question: is it possible to automagically graphs all metrics for an host like collection3 ?

### ISSUE THREAD

**Issue by TomGudman** [facette/facette#217]
Hi,

At the moment we are using collection3 which is terribly slow and exceptionally ugly. The complete opposite of facette ;-) However it does something very well. It lists all metrics for a host in one page. I am unsure if it is the purpose of facette to do that automatically or if we have to manually create each graph or generate JSON file to make that happen (I dunno how yet anyway). 

So far we only use facette for specific graph we build (combine different entries) but for all other metrics it will be good to have them graph by default. I tried to think about facette templating but I struggle to see how we can leverage template to make happen what I need. 

Any ideas or insights are welcome

PS: I am aware that facette is not PROD ready but still I like it and I fully understand that what I am asking may be impossible or not in the roadmap. I am just after some help to understand the feasibility of the thing (at the moment I am running 81fd3f8db7 in a docker instance).

Again thanks for sharing facette and for your great work!

**Comment by TomGudman** [comment]
Maybe this would be possible once #170 is done because we could have one collection per host? Am I right to say that?

**Comment by falzm** [comment]
Hi @TomGudman 

We do understand your pain with collection3, as a matter of fact using it extensively ourselves is the reason why we've created Facette ;)

At the moment it is not possible to achieve what you're asking for, although you're right – collection templates would allow users to mimic collection3's behavior. Collection template implementation is a bit trickier than graph templates, but we're not far from getting it done – please bear with us.

Thank you for your kind words.

P.S.: @vbatoufflet and I are using Facette in production for quite some time now, it helps driving bug fixes and improvements with real feedbacks!

**Comment by TomGudman** [comment]
So I am stuck with collection3 then...

**Comment by falzm** [comment]
I'm afraid so, stay tuned for upcoming updates!

**Comment by TomGudman** [comment]
Thanks for your quick answer

**Comment by tbleiker** [comment]
I am looking for this feature as well! :smile: I am quite happy with CGP. But I use facette for some custom graphs. Would be great to use facette only :smile: 

btw, you're doing a really great job!
