### ISSUE TITLE
Template problem when source is a "source group"

### ISSUE THREAD

**Issue by fcauvet** [facette/facette#218]
Hi facette team !

Thank you for your amazing work, facette has a lot evolved since then ;)

I have an issue regarding template source, it seems that I can not use a defined "source group" as a template source. The "source group" is not find when filling the source attribute when adding a graph from a template.

    2015/06/04 18:12:25 DEBUG: serveWorker: "POST /api/v1/plots HTTP/1.1" 200`
    2015/06/04 18:12:27 DEBUG: serveWorker: "GET /api/v1/library/graphs/?filter=test HTTP/1.1" 200
    2015/06/04 18:12:28 WARNING: server: unknown source `fr' for origin `collectd'
    2015/06/04 18:12:28 DEBUG: serveWorker: "POST /api/v1/plots HTTP/1.1" 200
    2015/06/04 18:12:30 WARNING: server: unknown source `fronta' for origin `collectd'
    2015/06/04 18:12:30 DEBUG: serveWorker: "POST /api/v1/plots HTTP/1.1" 200
    2015/06/04 18:12:41 WARNING: server: unknown source `frontau' for origin `collectd'
    2015/06/04 18:12:41 DEBUG: serveWorker: "POST /api/v1/plots HTTP/1.1" 200`

For information I am getting facette from the wheezy package '0.3.0-1~rc1~wheezy' under golang 1.3.3.
Would you want me to switch to the master branch instead of the provided package ?

Bisous bisous.
F.

**Comment by falzm** [comment]
Hi @fcauvet!

To access a source or metric group in a template attribute, you have to prefix the name with `group:` – i.e. I guess for your test case it would be `group:frontau`. Can you confirm it's working this way?

BTW trying to reproduce your issue allowed me to find another bug ;) (#219).

**Comment by fcauvet** [comment]
Hi @falzm ,
Indeed, prefixing the name with `group:` solved my issue.

Thank you for your quick answer.
