### ISSUE TITLE
Source groups series legends are missing expanded sources

### ISSUE THREAD

**Issue by falzm** [facette/facette#219]
When composing a graph featuring a series with a source group, the resulting graph legend doesn't expand the source groups per series.

Reproducible on http://demo.facette.io with a source group globbing sources `*.example.net`, composing a graph with a single series `load.shortterm`: 

![screen shot 2015-06-04 at 22 29 13](https://cloud.githubusercontent.com/assets/1122379/7993817/2a89efa2-0b09-11e5-89f4-38353344c9bc.png)

Resulting graph doesn't show the sources in the legend:

![screen shot 2015-06-04 at 22 28 46](https://cloud.githubusercontent.com/assets/1122379/7993820/2e61d306-0b09-11e5-9278-cfdf3ecfed61.png)

**Comment by vbatoufflet** [comment]
Fixed in 492e5ca5a0b205248f73931088163c328ab371c2.
