### ISSUE TITLE
Graph link are not create when using template

### ISSUE THREAD

**Issue by fcauvet** [facette/facette#223]
Hi Facette team,

When a graph is created from a template and added to a collection, the link to this graph is not added to the collection on the left part of the interface.

You could see my test on your demo, I have created a "collection test" with only one graph from a template and the link part is empty while the graph is shown.

I also have tested to add the graph "test" to the existing collection "host1.example.net" and the problem is the same.

Regards.

F.

**Comment by falzm** [comment]
Hi @fcauvet 

This is a known problem (#204), fix is already shipped in the master branch – version 0.3.0rc2 should be out very soon (hint hint @vbatoufflet :smirk:).
