### ISSUE TITLE
provide packages for debian jessie

### ISSUE THREAD

**Issue by landryb** [facette/facette#228]
facette is awesome, and the fact that you provide debian packages directly on github even more awesome.. but can you also build packages for debian jessie ? I have to admit i havent tested the wheezy package on jessie yet, but i doubt itd work...

**Comment by vbatoufflet** [comment]
Hi Landry,

We plan to build Jessie packages along with the soon to be released 0.3.0 (it has been a bit delayed, but we will try to release it the week to come).

BTW, I personally tested the Wheezy package on my Jessie servers at work, and at the time it worked like a charm :smile:

**Comment by landryb** [comment]
Ok, so i can safely upgrade my wheezy to jessie, that'll allow me to dogfood 0.3.0rc1 there ! Thanks !

**Comment by landryb** [comment]
I can confirm that 0.2.2 package for wheezy works fine on jessie

**Comment by vbatoufflet** [comment]
Debian Jessie packages have been shipped along with the [0.3.0 release](https://github.com/facette/facette/releases/tag/0.3.0).

**Comment by landryb** [comment]
And i can confirm this 0.3.0 packages work like a charm on jessie/i386, thanks!
