### ISSUE TITLE
Support for multiple x-axes

### ISSUE THREAD

**Issue by psytra** [facette/facette#230]
Hi All,

I'd like to share an idea with you. For me, a common use case when there is a performance problem, is to compare the current time frame with the same frame the previous day/week/month.

So I thought about having multiple x-axes in a graph would be neat.. Here's a screenshot of a protoype I've made:

![facette-multi-x-axes](https://cloud.githubusercontent.com/assets/1681739/8442882/2db1866c-1f82-11e5-9359-c156a6c6cbc9.png)
Idea is to have dashed or dotted lines for the secondary plot time-range.

Right now, I've implemented it by retrieving a second plot with a modified timerange.
However this could also be implemented at backend level, I think.
OTOH comparing time-ranges is a dynamic process, which should not require edit/save cycles.

With lots of metrics it probably gets messy, but having the data in one graph, and not, for example, in the same collection would be a benefit, I think. Problem: Getting it to work with all bells and whistles (like zooming, etc) will probably be a lot of work.

Ideas?

**Comment by falzm** [comment]
Hi @psytra 

A long time ago we thought about a "time shifting" feature (#67), would it be related to your idea?

**Comment by psytra** [comment]
Hi,

Yes that seems to be duplicate then.
Sorry didn't find it in my searches. Must have missed the right terms...

**Comment by falzm** [comment]
Thank you for elaborating you idea ;) We're definitely want to implement this feature, we're only lacking time to do so right now.

**Comment by TomGudman** [comment]
+1 
Also how did you do managed to have dashed lines with facette?

**Comment by psytra** [comment]
Hey Tom,
the dashed lines are a highcharts feature that is not configurable in
facette, yet. But it shouldn't be too hard to enhance the colorpicker with
line styles.

Unfortunately the multi x-axes feature is far away from being an acceptable
pull request...

**Comment by TomGudman** [comment]
Hi Psytra,
Thanks for the dashed lines tip!

**Comment by vbatoufflet** [comment]
Relates to #67.
