### ISSUE TITLE
Question: Scales and Units

### ISSUE THREAD

**Issue by TomGudman** [facette/facette#232]
Hey guys,

Can you explain or show me where in the documentation the use of Scales and Units. So far it is a bit unclear what the feature is/are. The names are obvious but I just can see the outcome. Any example? 

Sorry for being the noob here but yeah... it's like the colour picker last time I could not find I guess, it will be dead obvious once you say it ... maybe. Cheers

**Comment by vbatoufflet** [comment]
Hi Tom,

There is no such documentation today.

Units and scales are defined per series, in the second step in graph creation pane:

![sshot-facette-unit_scale](https://cloud.githubusercontent.com/assets/598433/8697912/985993a6-2af9-11e5-95a2-4ab2823c7339.png)

 * __units__ are displayed in legends on the series on which they are applied
 * __scales__ are useful if you want to apply a factor on series like `0.125` (from bits to bytes) or `8` (from bytes to bits)

If you define some scales and units in the dedicated panes in the Administration Panel it will make them available in the select menus to be used with series.

Is it more clear with this quick explanation :smile: ?

**Comment by TomGudman** [comment]
Yes, thank you. It is clear. Cool cool. Thank you for taking the time to answer.
