### ISSUE TITLE
Please keep read_only and JSON for the Catalog around

### ISSUE THREAD

**Issue by trehn** [facette/facette#233]
Just a little feedback here: Facette looks fantastic and I'm very excited to roll it out once support for InfluxDB 0.9 makes it into a release.

I'm opening this issue just to raise awareness for a use case that unfortunately gets overlooked in a lot of similar software: config management.

We manage three datacenter locations and will be deploying Facette at each one. Even with templates, I don't want to worry about keeping the three instances in sync. We use BundleWrap to manage all our other configuration (backup, monitoring etc.) and it is pretty important to me that we can automatically add new hosts to Facette.

Currently, we can do that by setting `read_only` in the global config and then generate JSON files to put in `/var/lib/facette`. The UUID filenames make it a bit harder, but that's OK.

So I'm just hoping that you won't introduce changes that complicate this, like storing some data in an SQL database, as Grafana does. If you could even add documentation for the contents of the JSON files for graphs etc. that would be awesome, but I understand that it might be too much hassle.

Feel free to close this issue immediately, just wanted to let you guys know how we're using Facette. Keep up the great work :)

**Comment by trehn** [comment]
Just saw that #227 is basically about the same thing, closing.

**Comment by vbatoufflet** [comment]
Hi Torsten,

We do not plan to remove the read-only feature :smile: 

That being said, we are looking and started to work on moving to a SQL-based backend. But the the other hand we plan to provide a way to dump/restore Facette's library through the `facettectl` utility.
