### ISSUE TITLE
Admin panel metric list sorting/filtering

### ISSUE THREAD

**Issue by xor-gate** [facette/facette#234]
It would be very nice to filter on _origins_ and/or _sources_ in the Metric list. Currently it is even not possible to search for a source(name) in the metric list and with alot of metrics this is very hard to manage by hand.

**Comment by vbatoufflet** [comment]
Hi Jerry,

On which list to you want to filter items from?

**Comment by xor-gate** [comment]
Admin panel -> Catalog -> Metrics -> Metrics list

**Comment by vbatoufflet** [comment]
Just to be sure, there should be a filter field on upper right corner saying “Search for Metrics”.

It should work as you describe it. Or I didn't catch the issue here :smile:

**Comment by falzm** [comment]
@vbatoufflet if I get it right I think Jerry would like to be able to filter the metrics list for a certain source/origin.

**Comment by vbatoufflet** [comment]
Oops, my bad! Ok :wink: 

So, something like “origin:collectd” or “source:host1.example.net” filters?

**Comment by falzm** [comment]
LGTM :+1:

**Comment by xor-gate** [comment]
@vbatoufflet yes this a very nice idea then the ui is not polluted but still there is filtering functionality ! I did not know what was a nice approach to add this functionality but totaly agree with yours.

**Comment by iaean** [comment]
Really great feature. :+1:
