### ISSUE TITLE
SystemD service file missing (e.g from debian packaging)

### ISSUE THREAD

**Issue by xor-gate** [facette/facette#236]
There is a facette.init supplied but newer versions of Debian and other distros use SystemD for process management. This is my working SystemD service configuration (On Arch Linux):

**/etc/systemd/system/facette.service**

```
[Unit]
Description=Facette

[Service]
User=facette
ExecStart=/opt/facette/facette-linux-amd64/bin/facette

[Install]
WantedBy=multi-user.target
```

Here is the specification of the SystemD service file:
http://www.freedesktop.org/software/systemd/man/systemd.service.html

**Comment by xor-gate** [comment]
Hi guys, I see this has not yet labeled. Still ideas to integrate this, so it will work for Debian 8.0 and other distros (systemd is default Init for debian 8) ?

**Comment by vbatoufflet** [comment]
Hi Jerry,

I didn't had the time to look into it yet. 

I don't use systemd on my various Jessie servers so I don't have any to test it right now. I will try to install one some day :smile:

**Comment by Artanicus** [comment]
Any update on this? systemd is starting to be default quite widely.

**Comment by falzm** [comment]
Hi @Artanicus 

Upcoming version 0.4.0 is about to be ready to released soon, it will feature a systemd service file.

**Comment by falzm** [comment]
Added in branch `0.4-alpha`.
