### ISSUE TITLE
Feature Request: Folding/rolling left menu

### ISSUE THREAD

**Issue by TomGudman** [facette/facette#238]
Hi,

This is a low priority feature request. 

Facette could be used on a dashboard (TV screen) by displaying several collections (e.g: rolling via a firefox tab plugin). The problem is the left menu which adds no value and takes room on the screen/dashboard. Ideally it would be good to roll it like we can roll/hide/fold legends in a graph. 

Thanks

**Comment by vbatoufflet** [comment]
This kind of behavior has been implemented on a new UI we are working on.

We'll see if it can be ported on the current one.

**Comment by TomGudman** [comment]
Re,

> This kind of behavior has been implemented on a new UI we are working on.
> We'll see if it can be ported on the current one.
As said, no hurries, it was just an idea, if you are working on your new 
UI maybe there is no need to backport the feature if the new UI is 
planned to be released in the coming months.

Thanks

**Comment by vbatoufflet** [comment]
Shipped in b33172f14a0b37eefe8324a4b430133d70f23241.
