### ISSUE TITLE
setting relative path in rrd providers will break facette in many different ways

### ISSUE THREAD

**Issue by vaab** [facette/facette#240]
I wanted to try relative path in ``path`` of a ``rrd`` ``connector``. I was surprise to hit several critical bugs:

In the process of trying to circumvent #239. I started to try relative paths as the ``path`` in the ``connector`` part of ``providers`` configuration. I noticed:
- ``facette`` then use the CWD of the process as base (this should be changed).
- values as ``.`` seems to mess with the regular expression used to infer source names.
- using other values gives many weird (bad) answers: 
    - ``..`` seems to make it go along a infinite recursive call, 
    - ``../db`` will cast:
```
2015/07/29 06:45:51 ERROR: provider: collectd-local: unable to refresh: lstat ../etc/modules-load.d/../modules: no such file or directory
```
- empty value will cast:

```
2015/07/29 06:51:06 ERROR: provider: collectd-local: unable to refresh: stat : no such file or directory
```

This makes me think that it seems this ``path`` variable is used in too many places and should not break so easily ``facette``.

At least a reasonable check should be done to forbid insane values.

**Comment by vbatoufflet** [comment]
Hi Valentin,

I fixed some issues with relative paths handling in the RRD connector, see 6c1e2cd4922c0209c40ace313d798f7457d5d13d.

Using either an empty value, `.` or `..` paths shouldn't break sources and metrics names detection anymore.

**Comment by vaab** [comment]
Why was this re-opened ? Seems to be related to 239 referencing this... Anyway, I couldn't confirm this was working until recently (because of 239). And this worked in my small test case. Thanks.
