### ISSUE TITLE
How can I draw some simple operation results between available values

### ISSUE THREAD

**Issue by vaab** [facette/facette#241]
Hi, this is a simple question...

I can get "swap_available" and "swap_total" numbers, but I want to draw "swap_used"... In other words, I just want to draw a line on "swap_total" minus "swap_available".

Is this possible with facette ? if yes, how ? if no, is it planned in some hypothetical future ?

**Comment by vaab** [comment]
I managed to do what I wanted by applying a negative scale to "swap_available", and created a SUM group between "-swap_available" and "swap_total" and named the group "swap_used".

Is that how it should be done ?

**Comment by vbatoufflet** [comment]
Hi Valentin,

Indeed it is actually the only way to do it. But we are aware that it's not very straightforward.

We didn't plan to implement this kind of operation when we developed Facette. But it is something we can discuss an implement.

**Comment by vaab** [comment]
I have more complex operation to do as dividing metrics with others, usage of constants of which I can't find any way to do.

**Comment by vbatoufflet** [comment]
The two operation types supported at the moment are SUM and AVG. The way  those features work today make it too complex to implement dividing.

If we want Facette to be able to perform more complex operations, we will have to rethink the way it perform calculations.

Regarding constants, I am not sure to understand what you are trying to achieve. Can you gives us some details?

**Comment by vaab** [comment]
> Regarding constants, I am not sure to understand what you are trying to achieve. Can you gives us some details?

Mostly around having inverses (1 - VALUE) for instance (OccupiedTimePercent = 100 - IdleTimePercent, or asking to show what's 90% of available space on a hard drive because an alarm is set on this mark). Or drawing lines on specific values to show for instance when some other alert will be spawned (For instance if hard-drive free space goes under 100Mo, I'd like to draw a line which symbolize this 100Mo)...

**Comment by vbatoufflet** [comment]
When you add a graph to a collection you can define in its options:
 * constants that will draw lines at the specified values
 * percentiles that will calculate the nth percentile and add it to the legend

About the operation you mention _1 - VALUE_, it is not supported right now.

**Comment by vaab** [comment]
Wow, I never noticed these options. Many thanks.
I guess that will do for half of my needs. But what puzzles me is why this option is in the collection side ? shouldn't it be on the graph responsibility ? What is the rationale behind this choice ? I feel like I missed something important there.

Is the literal (constant) usage as I described the same complexity to achieve than operation like dividing between variables ?

**Comment by falzm** [comment]
@vaab the rationale for collection graph options is that it is sometimes useful to specify some graph options in the context of a certain collection, this way a graph can remain kind of neutral and be customized when "instanced" in a collection.

**Comment by vaab** [comment]
Ok, many thanks for your answer. I'll close this thread as I understood that you are not planning currently to go further on implementing more on the operation side, and you've answered my questions.
