### ISSUE TITLE
Some complex operation seem to have a different timestamp resulting in saw type graph

### ISSUE THREAD

**Issue by vaab** [facette/facette#242]
I have a complex graph with many metrics. In the resulting graph, I have distinctely a saw effect as all my direct values are stacked on the correct timestamp, and one second later I get some complex values (like SUM with element having negative scales and others).

![values1](https://cloud.githubusercontent.com/assets/703255/9008804/03b06d64-379d-11e5-934e-7e220934c7bd.png)

![values2](https://cloud.githubusercontent.com/assets/703255/9008803/03acea0e-379d-11e5-88db-fc5f427ba61c.png)

Notice also that as a consequence the height of the dots seems to have been averaged. For instance, RAM available is 2.06 in all displayed values, but it is distinctively drawn at around 1.3GB.

Please note that the 2 values that are drawn alone are both complex value.

Resident is a complex calculus from `Resident = (TotalRam - FreeRam) - Buffered - Cached - Shared`.

I did this by inverting all metrics that had to be subtracted by using a negative scale at first, then I grouped all of these into a SUM group.

`SWAP Used` is simpler but uses the same trick: `SWAPUsed = SwapTotal - SwapFree`.

Am I doing something wrong ?

Obviously all values have the correct timestamp in `collectd` side as most of them are displayed in a STACKED group and are all together.

Where does this second timestamp come from in these computed values ?

**Comment by vbatoufflet** [comment]
As replied in #241, this kind of subtraction is more a hack than an actual feature.

That said, when Facette performs operations on series, it starts by normalizing them into plot buckets (to ensure each series has the same precision), and then applies a consolidation function on each of those buckets.

Depending of the metric data type, the default _Average_ consolidation might not be the most suitable one. And you can chose any of _Min_, _Max_, _Last_ or _Sum_ instead in the graph creation pane.

It's also possible that the tweak you used to perform subtraction has some weird side effects on Facette behavior when calculating plots.

We will have to investigate on this.

**Comment by vbatoufflet** [comment]
This use-case won't be addressed as we would like to remain generic in the way of handling time series calculations.
