### ISSUE TITLE
facette rrd discovery algorithm vulnerable to endless recursive loop

### ISSUE THREAD

**Issue by vaab** [facette/facette#244]
If you have an endless recursive loop with symlinks, facette will follow it to eternity.
And you can't `Ctrl-C` or `kill` it, only `kill -9`, this is annoying.

Suggestions:
- follow symlink but keep track of real path and those you've already seen.
- (OPTIONAL) provide a way to actually listen to `Ctrl-C` and `kill` while parsing files.

my 2cents,

**Comment by vbatoufflet** [comment]
Hi Valentin,

I'll see what can be done to respond to the `SIGKILL` signal while walking the filesystem to look for `.rrd` files.

But keeping track of all files already processed and looking at the list for each new processing to see if it was already seen will IMHO add so much overhead when walking large file trees.

**Comment by vaab** [comment]
We are only talking of directory (not files). And I guess the user will wait much more on IO of the disk than on the CPU/Memory dialoging. You would require a really special setup (very rare setup) without really loads of directory (probably several tens of thousands) to make the overhead noticeable. Meanwhile the people having one single recursive link would have to ``Ctrl-C`` or to ``kill`` facette... FYI this happened me twice in a few weeks of usage of facette (mainly because I tried to use relative ``path`` in RRD provider's config files and that the source code of facette uses looping symbolic links, but it also happened in ``/tmp`` because having looping symbolic links is a pretty common case.)

I guess that it won't hurt me if you don't wish to tackle this issue. Here are other tracks of thought you maybe already had:
- You can put a max recursion depth limit (but this will require some way to change it, and the documentation of it... please notice that all of that could be contained in the error message printed to the user when hitting the limit). This options could be part of the configuration of the 'rrd' provider, and might make sense along with the regex used to infer 'source' and 'metric' names. Both of these options require some knowledge of how the files/directory are organized in your target ``path``. A sane default could be used (32?). Bear in mind that find metric in such a deep hierarchy would generate insane metric names in the default regex case. These would render most of the UI design unusable in more than one way (I'm struggling with some aspect of this today with only a depth of 2).
- You could avoid to follow symlinks or make it configurable. (this wouldn't protect you from hardlink recursion... but well... this is much less used.)

Many thanks anyway for your attention on this subject.

**Comment by vbatoufflet** [comment]
I'll the issue for now. Please reopen if still relevant.
