### ISSUE TITLE
feature: Collection template

### ISSUE THREAD

**Issue by vaab** [facette/facette#245]
I found my self having to recreate dozens of collections with exactly the same templated graphes.

For instance, I did 5 templated graphs following different metric around a docker instance (cpu, memory, io, network ...). The only template variable is the name of the docker. Template graphs where tremendously useful already in this first stage.

But when I had to put all graph together in a collection, I found myself in dire need of the same feature for collections. I want to aggregate the exact same 5 graphs and I have to do it for each new docker instance I have. I figured that a template collection would only require me to fill the name of the docker, and the 5 graphs could then be fed the correct values.

What do you think about this ?

**Comment by falzm** [comment]
Work in progress, see https://github.com/facette/facette/issues/170 ;)

**Comment by vaab** [comment]
Ok, so this is a duplicate. Thanks.
