### ISSUE TITLE
SQL-backed library storage

### ISSUE THREAD

**Issue by falzm** [facette/facette#246]
Currently the backend library items are stored as JSON-serialized files on the local filesystem. This was practical in the beginning, but it now comes as a limitation. Storing the library in a SQL-based datastore such as SQLite, MySQL or PostgreSQL would allow better easier constraints checking, e.g. linking items together or checking uniqueness.

**Comment by iaean** [comment]
Hi @falzm,

please still provide filesystem storage as an alternative or addon. It's a really easy place to lookup data structures during development of apps using facette's REST API...

**Comment by falzm** [comment]
Hi @iaean 

I'm afraid this won't be possible eventually: the library is in the process of being incorporated in this layer of SQL-backed storage, some low-level library mechanisms will depend on ACID properties.

This change should be transparent at the API level. Besides, Inspecting a SQLite database is not much more complicated than reading files on a filesystem IMO.

**Comment by vbatoufflet** [comment]
@iaean we also plan to allow library items manipulation through the `facettectl` utility.

**Comment by iaean** [comment]
@falzm: Ack. REST API lookups are fine. But hoping there 'll be another easy way to view the stored backend JSON as consolation gift... ;) I'm curious about it.

@vbatoufflet: ...my curiosity was piqued. Why library manipulation via `facettectl`, too? I'ld prefer focus on stable REST API. With that, manipulation is easy as `facettectl` on local systems, too.
If you like, I could contribute and maintain some node scripts for that...

**Comment by falzm** [comment]
@iaean the management API currently under work (#199) would allow dumping/restoring the whole library for backup purpose, you could use it to "access" the raw data.

Regarding the `facettectl` utility, it will also use the management API undercover and allow among other actions to create/query the library from a CLI – might be useful for instance for configuration management provisionning.

**Comment by xor-gate** [comment]
Sqlite would be a nice option because it doesn't need any configuration, still when you want to replicate or backup in a easy way MySQL or PostgreSQL would be a better option it also (but those are much bigger). I found this nice Sqlite replication written in Go: https://github.com/otoolep/rqlite 

It depends if you also want to support running Facette on a Embedded-like platform (with good performance) e.g Raspberry Pi. And MySQL or PostgreSQL will need more resources.

**Comment by falzm** [comment]
@xor-gate backup/restore are currently being implemented in the `facettectl` utility so that it will abstract the DB actually used as backend: it will dump the instance settings and the library in a file that can be stored as the user's convenience.

Thanks for rqlite BTW, interesting project :)

**Comment by falzm** [comment]
Implemented in branch [0.4-alpha](https://github.com/facette/facette/tree/0.4-alpha).
