### ISSUE TITLE
ability to select mulitple metrics at "New Graph"

### ISSUE THREAD

**Issue by kiranos** [facette/facette#248]
Now I have to type \* to get all available metrics for a specific source and then add them one by one, It would save alot of time to be able to hold down shift/ctrl and arrow down to select multiple metrics

**Comment by TomGudman** [comment]
+1
It makes creating graphs very tedious which is a shame because facette is a great product to use but the graph creation, despite templates is very long.

**Comment by falzm** [comment]
Hi

Could using metric groups solve your problem, for the time being?

**Comment by vbatoufflet** [comment]
Sources and metrics groups should cover this matter.
