### ISSUE TITLE
Displayed values 10 times less than they are.

### ISSUE THREAD

**Issue by TomGudman** [facette/facette#249]
Hi,

I have just tried to graph the output of a collectd interface plugin to see the throughput of a box (e.g: net.eth0.octets.tx). It works except the values are off by 10^-01 ... So it is 10x less than the real value in the RRD file, eg: 80mbps is displayed as 8mbps. I have no scale setup. I am using facette c36c7f27fa.

```
# cat 13046089-4301-4eb3-4189-12b1b34b23ba.json 
{
    "id": "13046089-4301-4eb3-4189-12b1b34b23ba",
    "name": "Throughput : XXXXXXX",
    "description": "",
    "link": "81799da2-2f13-4325-44d1-e32b67d656aa",
    "attributes": {
        "source": "XXXXXXX"
    },
    "template": false
}

# cat 81/79/81799da2-2f13-4325-44d1-e32b67d656aa.json 
{
    "id": "81799da2-2f13-4325-44d1-e32b67d656aa",
    "name": "Throughput and errors (net.*)",
    "description": "",
    "title": "{{ .source }} Throughput and errors",
    "type": 1,
    "stack_mode": 1,
    "unit_type": 2,
    "groups": [
        {
            "name": "net.eth0.octets.rx",
            "type": 1,
            "stack_id": 0,
            "series": [
                {
                    "name": "net.eth0.octets.rx",
                    "origin": "collectd",
                    "source": "{{ .source }}",
                    "metric": "net.eth0.octets.rx",
                    "options": null
                }
            ],
            "options": {
                "scale": 1
            }
        },
        {
            "name": "net.eth0.octets.tx",
            "type": 1,
            "stack_id": 0,
            "series": [
                {
                    "name": "net.eth0.octets.tx",
                    "origin": "collectd",
                    "source": "{{ .source }}",
                    "metric": "net.eth0.octets.tx",
                    "options": null
                }
            ],
            "options": {
                "scale": 1,
                "unit": ""
            }
        },
        {
            "name": "net.eth0.errors.rx",
            "type": 1,
            "stack_id": 0,
            "series": [
                {
                    "name": "net.eth0.errors.rx",
                    "origin": "collectd",
                    "source": "{{ .source }}",
                    "metric": "net.eth0.errors.rx",
                    "options": null
                }
            ],
            "options": {}
        },
        {
            "name": "net.eth0.errors.tx",
            "type": 1,
            "stack_id": 0,
            "series": [
                {
                    "name": "net.eth0.errors.tx",
                    "origin": "collectd",
                    "source": "{{ .source }}",
                    "metric": "net.eth0.errors.tx",
                    "options": null
                }
            ],
            "options": {}
        }
    ],
    "template": true
}
```

PS: I added scale = 1 via the interface just to see if it works better

I can provide the RRD file if required.

**Comment by vbatoufflet** [comment]
Hi @TomGudman,

It could be great indeed if you could provide us with the RRD file.

**Comment by TomGudman** [comment]
On 14/08/15 14:46, Vincent Batoufflet wrote:
> Hi @TomGudman <https://github.com/TomGudman>,
>
> It could be great indeed if you could provide us with the RRD file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facette/facette/issues/249#issuecomment-130964631>.
>

See attachment.

**Comment by TomGudman** [comment]
Github noob here. I did not know it does not support file attachment. 
Here is the link to get the RRD:  http://bogan.dmw.fr/~tom/if_octets.rrd

**Comment by vbatoufflet** [comment]
Hi Tom,

I configured the same graph template and instance than yours using the information you provided us with, only removing errors as I do not have the data for it.

Here is the resulting graph: 
![if_octets-render](https://cloud.githubusercontent.com/assets/598433/9486209/6f51ea44-4bc4-11e5-8c43-68e9f8058f49.png)

Are the values incorrect?

**Comment by TomGudman** [comment]
I did not take any picture of the rendered graph, I should have. 
I cannot reproduce so it must be a PEBKAC

Resolving for the time being.

**Comment by TomGudman** [comment]
Forgot to say something very important! Thank you for spending time looking into it especially when this could be just me hallucinating...
