### ISSUE TITLE
Deleted Sub-Collections not removed from Root Collection

### ISSUE THREAD

**Issue by iaean** [facette/facette#250]
Hi,

I have just deleted all Items under a specific Root Collection by script via facette's REST API. But in the GUI the Subcollections of the Root Collection are still remaining... Seems to be a GUI backend bug.

![1st](https://cloud.githubusercontent.com/assets/10342186/9255732/7fd50870-41eb-11e5-8836-5ae17b99873a.PNG)
![2nd](https://cloud.githubusercontent.com/assets/10342186/9255731/7fd2d4ce-41eb-11e5-8637-98ccca3cb8c9.PNG)

**Comment by vbatoufflet** [comment]
Thanks for the bug report. It has been fixed in 06ebabf024dbce17f3b3a39f2c8f9353218d3a35.
