### ISSUE TITLE
autodiscover feature to create graphs from rrd's

### ISSUE THREAD

**Issue by kiranos** [facette/facette#251]
It would be nice to have precreated templates for the most common collectd plugins, and that we can choose to use these to get up and running fast, after we can manipulate the settings for the graphs to fit our liking but, having such a feature would be really nice.

**Comment by falzm** [comment]
Agreed, this is something we should be able to provide. Thank you for suggesting it.

**Comment by falzm** [comment]
I wonder if this is something we should offer at packaging level. WDYT @vbatoufflet?

**Comment by vbatoufflet** [comment]
We'll have to see how to achieve this as generic as possible, not only for Collectd.

But yeah, it could be something interesting.

**Comment by vaab** [comment]
Actually, the very primitive way to discover ``rrd`` files and assign them to ``source`` and ``metric`` is perfect and could provide a very convenient way for filling availables templates. What could be done is from the template edition form (graph, and/or collection templates), you could provide an check mark to open an "autofill template vars with given regex", you ticked, a text input could be provided for the user to fill with a regex that would be then applied to any source/metrics available to create graphs.
The best would be that these graphs were NOT created, but available dynamically.

**Comment by tirra** [comment]
This would be awesome!

**Comment by TomGudman** [comment]
+1 

Related to #217

**Comment by vbatoufflet** [comment]
Related to #266.
