### ISSUE TITLE
direct link to a particular graph in a specific panned and zoomed state

### ISSUE THREAD

**Issue by vaab** [facette/facette#253]
Is there a way to get a direct link to a specific graph in a specific state ? I could take also a direct link with specific POST variables if necessary. Please note that my main issue is to get an export of the given graph in this specific state.

If this is not possible, how about considering this as a feature in next releases ?
If this is possible, did I miss a documentation on this somewhere ?

**Comment by vbatoufflet** [comment]
Hi Valentin,

It could be considered yes. It's not feasible right now.

**Comment by vbatoufflet** [comment]
Embeddable graphs will now handle “time” and “range” arguments in URLs.

See 7d8fd80db742e83772ab6a619f342c8e6eaa4200.
