### ISSUE TITLE
facette can not be proxied to

### ISSUE THREAD

**Issue by akosiaris** [facette/facette#255]
At least in apache2 I had problems proxying it. Configuration

```
ProxyPass     /facette     http://127.0.0.1:12003 retry=0
ProxyPassReverse /facette    http://127.0.0.1:12003 retry=0
```

Result when visiting http://server_ip/facette is getting a `301` redirecting to https://server_ip/browse/ which is obviously wrong

**Comment by vbatoufflet** [comment]
Hi Alexandros,

Did you set `url_prefix` to `/facette` in your configuration?

See [Base Settings](http://docs.facette.io/configuration/#toc_1) for further details.

**Comment by akosiaris** [comment]
Hello, yes I did. My facette configuration (forgot to paste it)

```
{
	"bind": ":12003",
	"base_dir": "/usr/share/facette",
	"providers_dir": "/etc/facette/providers",
	"data_dir": "/var/lib/facette",
	"pid_file": "/run/facette/facette.pid",
	"url_prefix": "/facette"
}
```

I am running `0.3.0-1~rc1` (hash 2c863b13b940efb603c8b733646505cdbeacc68c) is this configuration term supported in this version ?

**Comment by akosiaris** [comment]
Scratch that, forgot to clear browser cache. Seems to be working now. Thanks and sorry for the fuss. Closing.

**Comment by vbatoufflet** [comment]
Ok, no worries :smile:
