### ISSUE TITLE
facette influxdb-0.9 panic: interface conversion

### ISSUE THREAD

**Issue by schulzh** [facette/facette#256]
I am trying out the influxdb-0.9 branch on RHEL7.
When starting facette, I get the following error:
`panic: interface conversion: interface is nil, not map[string]interface {}`.
The full log can be found here: https://gist.github.com/3vILVIrUs/c1784d7b98a9b35b8c9a
This is the configuration I use:
`/etc/facette/facette.json`:

>    {
>         "bind": "tcp://0.0.0.0:12003",
>         "base_dir": "/usr/local/share/facette",
>         "data_dir": "/var/lib/facette",
>         "pid_file": "/var/run/facette/facette.pid",
>         "providers_dir": "/etc/facette/providers",
>         "read_only": false
>     }

`/etc/facette/providers/monsoon_influxdb.json`:

> {
> "connector": {
> "type": "influxdb",
> "url": "http://hcidiscovery.mo.sap.corp:8086",
> "username": "root",
> "password": "root",
> "database": "anaflow",
> "pattern": "(?P<source>[^\\.]+)\\.(?P<metric>.+)"
> }
> }

**Comment by vbatoufflet** [comment]
The `influxdb-0.9` branch has been updated but the configuration format changed for this connector.

We are working on having on finalizing it and if possible make it compatible with old configuration format.

**Comment by xor-gate** [comment]
It also seems with current facette release 0.3.0 and influxdb 0.9.0 we get a 404 error because the API has changed. This will be resolved also then in facette 0.4.0 milestone.

**Comment by lola27** [comment]
I got the same issue. 

2015/10/27 11:37:21 ERROR: provider: influxdb: unable to refresh: influxdb[influxdb]: unable to fetch series list: Server returned (404): 404 page not found

**Comment by vmercierfr** [comment]
Do you have any news about this issue?

Thanks

**Comment by jonas-koeritz** [comment]
Please provide an example for the new "mapping" configuration.

**Comment by falzm** [comment]
Support for InfluxDB 0.9.x will be discarded starting at Facette 0.4.x; support for InfluxDB 1.x implemented in branch [0.4-alpha](https://github.com/facette/facette/tree/0.4-alpha).
