### ISSUE TITLE
Add automatic refresh on standalone graph view

### ISSUE THREAD

**Issue by falzm** [facette/facette#258]
For dashboard purposes it would be handy to be able to pass arguments to a standalone graph, such as a refresh interval or a time window range.

**Comment by falzm** [comment]
Parameters `range` and `time` have already been implemented. TBD: implement refresh on standalone graph view.

**Comment by vbatoufflet** [comment]
Shipped in 6af1641a548e112f21870999b4c51f75b80aa93b.

**Comment by falzm** [comment]
\o/
