### ISSUE TITLE
RRD connector read remote RRDtool files

### ISSUE THREAD

**Issue by lola27** [facette/facette#259]
Hi, i want to use the RRD connector to read RRDtool files to extract stored metrics. while my rrd files are stored in a remote server. is that possible to connect to a remote server to read those rrd files?   if it is possible, then how to definite the provider?  Thanks.

```
{
	"connector": {
		"type": "rrd",
		"path": "/var/lib/collectd/rrd",
		"pattern": "(?P<source>[^/]+)/(?P<metric>.+).rrd"
	},

	"filters": [
		...
	]
}
```

**Comment by falzm** [comment]
Hi @lola27 

You can use the [Facette connector](http://docs.facette.io/configuration/connectors/) : install a Facette instance on the remote server where RRD files are stored (configured to use the RRD connector), and configure another Facette instance configured with the Facette connector to forward requests to the other instance.

Let us know if you need more information.

**Comment by lola27** [comment]
Thanks @falzm! 
i am intend to monitor more than one remote server. so maybe it is not good to install Facette into every servers.

**Comment by falzm** [comment]
I don't know how you collect your metrics but storing them directly on every server will quickly become unmanageable IMO... You should consider using something like [collectd](http://collectd.org/) and its 'network' plugin to centralize RRD files on a single server.

**Comment by lola27** [comment]
I actually used collectd, and used the 'network' plugin to send data to influxdb. but i got a problem #256 . So i try to skip influxdb.

**Comment by falzm** [comment]
You could also use the network plugin to send your servers' collected metrics to a central collectd instance that writes RRD files locally, and use Facette on this server?

**Comment by lola27** [comment]
okay. it seems possible. i will try to do that. thanks @falzm !

**Comment by falzm** [comment]
You're welcome :) We'll try to fix the InfluxDB connector so it's compatible with the latest API changes – hint hint @vbatoufflet.
