### ISSUE TITLE
Inadequate documentation

### ISSUE THREAD

**Issue by mgedmin** [facette/facette#262]
I'm trying Facette for the 1st time, and I'm very impressed.  However I also feel lost.

I've built, installed and configured it.  I can see it finds my collectd rrd files in the catalog.  Howerver I have no graphs.  Am I supposed to define them by hand?  Can this be automated?

Additionally, I've no idea what "units", "scales", "metric groups", "source groups" are, or in what order I'm supposed to be defining things.  This doesn't seem to be documented at http://docs.facette.io/

**Comment by falzm** [comment]
Hi @mgedmin 

Thank you for your feedback, very useful. We deliberately avoiding documenting the usage of the web interface assuming it would be intuitive enough to use. Looks like we were wrong :)

On the plus side, we also documented how to make your first steps using Facette on our blog with the *Using Facette* post series: https://blog.facette.io/tag/using-facette/

Let us know if it helps, otherwise we should go the extra mile and also document the web interface usage in the official documentation.

**Comment by mgedmin** [comment]
The web interface is intuitive!  The problem is that I don't know what the various concepts mean.

I've figured out how to add a couple of graphs and a collection.  I still have no idea how to create graph templates, or what those other things are.

**Comment by falzm** [comment]
The template usage is also documented in a blog post at the address linked previously; regarding the secondary objects usage (metrics, scales, groups...), we could also write a blog post on this topic...

**Comment by mgedmin** [comment]
Do you think you could add links to those blog posts so they could be discovered by people browsing the documentation at http://docs.facette.io/?

(Is the documentation maintained on GitHub?  I wanted to submit a quick PR for the nodejs advice on Debian/Ubuntu: `apt-get install nodejs-legacy` is shorter and simpler than manually invoking `update-alternatives` to get `/usr/bin/node`).

**Comment by falzm** [comment]
You're right, we will link the blog posts from the main documentation: https://github.com/facette/facette-docs/issues/16

Documentation is indeed on Github too, PRs welcome: https://github.com/facette/facette-docs

**Comment by mgedmin** [comment]
BTW do you have any community meeting places (IRC, Slack, Gitter)?

**Comment by falzm** [comment]
No, we never really took the time to setup any community-related tool... Now might be a good time :)

**Comment by falzm** [comment]
Documentation has been updated: http://docs.facette.io/usage/#going-further
