### ISSUE TITLE
Legend: maybe don't use different symbols for area graphs?

### ISSUE THREAD

**Issue by mgedmin** [facette/facette#263]
I'm only filing this issue because Facette's UX is so impressive even the littlest details stick out.

When you define an area graph, the legend looks a bit out of place:

![ekrano nuotrauka is 2015-11-06 15-21-50](https://cloud.githubusercontent.com/assets/159967/10997960/202a7fc6-849a-11e5-8b3e-accf54232f33.png)

It would be better if the legend showed little squares instead of circles/diamonds/triangles that are probably used to show data points when you choose a line graph.

**Comment by TomGudman** [comment]
I disagree. When the lines are really entangled, these shapes are useful because you cannot distinguish the lines by the colors.

**Comment by vbatoufflet** [comment]
Symbols are no longer available in [0.4-alpha](https://github.com/facette/facette/tree/0.4-alpha) as we changed the library used to generate graphs to d3.
