### ISSUE TITLE
Better color selector?

### ISSUE THREAD

**Issue by mgedmin** [facette/facette#264]
I've defined a graph for showing swap usage:
![ekrano nuotrauka is 2015-11-06 15-54-41](https://cloud.githubusercontent.com/assets/159967/10998585/c0ebbd90-849e-11e5-9f95-cbbbf804e2f7.png)

The default colors do not work very well for this.  I'd like to change the swap.cached to something else.

Here's what I have to do:
- click the edit icon (nice)
- click the edit template icon (nice, although I didn't notice it at first)
- click Next
- click on the little contrast symbol next to swap.cached
- click the color selector (Chrome renders it like this):

![ekrano nuotrauka is 2015-11-06 15-57-26](https://cloud.githubusercontent.com/assets/159967/10998629/1bd3379c-849f-11e5-8b27-ae087459bde9.png)
- click the weird-looking box-with-a-smaller-box (it's actually `<input type="color">`)
- pick a color in the modal color selection dialog (implemented by Chrome):
  ![ekrano nuotrauka is 2015-11-06 15-58-19](https://cloud.githubusercontent.com/assets/159967/10998647/4188874e-849f-11e5-93f3-970a6f4220f3.png)

What makes me sad:
- the pre-selected color is white instead of what actually gets used in the current graph
- the color selector is based on RGB and not HSV (but you can't do anything about it, short of not using `<input type="color">`)
- there are no presets

E.g. if I wanted to swap the colors, I'd have to take a screenshot, open it in an image editor, discover the RGB values used for the default colors, then enter them.

**Comment by mgedmin** [comment]
Swapping the colors is also a bit unpleasant, even after I figure out the RGB values.

**Comment by vbatoufflet** [comment]
Hi Marius,

We are working on a new UI version.

The new color picker present in it won't use the builtin `<input type="color"…>` element and will be fully integrated to the UI.

I guess we can think of a way to save some predefined colors and/or a list of the _n_ last picked colors.

**Comment by mgedmin** [comment]
AFAIU currently the default colors get picked by HighCharts, is that right?  Having the color picker list these (or maybe just the first 10-20, if there are many), plus an option for a custom color, would be nice.

**Comment by vbatoufflet** [comment]
Addressed in [0.4-alpha](https://github.com/facette/facette/tree/0.4-alpha).
