### ISSUE TITLE
Usability: remember template attributes used for previewing

### ISSUE THREAD

**Issue by mgedmin** [facette/facette#265]
It's a bit annoying to have to re-type the host name just so that I can preview a template.  It'd be nice if those were remembered from last time.

**Comment by vbatoufflet** [comment]
I guess it feasible.

But there are several possibilities here:
 * store them as preview attributes along with the template (but strictly speaking, they are not really part of the template data)
 * remember the value locally in the browser storage

**Comment by mgedmin** [comment]
There's also an option of just guessing for a valid value.  E.g. if the template attribute is used in the source field, pick a random source.  Same for metric.  For attributes used in title/description, some random words would suffice (e..g "title", "description").

Smarter matching might be required if the variable is used not directly but just as part of the value, e.g. for metric = "net.{{ .iface }}.octets.rx" you'd have to filter all the available metrics for those that match a regexp "^net\.(.*)\.octets\.rx$" and then use the captured group as the default template attribute value.

Pros: no extra data needs to be stored; the preview is available immediately without any extra user action.

Cons: harder to implement maybe.

**Comment by vbatoufflet** [comment]
Indeed, such implementation will add complexity and won't be easy to implement.

Thinking of that, maybe we can fill the fields with values from an already existing instance of this template only if there is one.

**Comment by mgedmin** [comment]
That's a brilliant idea!

**Comment by vbatoufflet** [comment]
Implemented in [0.4-alpha](https://github.com/facette/facette/tree/0.4-alpha).
