### ISSUE TITLE
Enable batch graph series (de)selection

### ISSUE THREAD

**Issue by falzm** [facette/facette#267]
Implement a button or a bindkey allowing a user to select or deselect all of a graph's series at once.

**Comment by xSmurf** [comment]
How about click once to show only that series, click twice to negate, click thrice to reset? That would be pretty logical and wouldn't require an extra ui element.

**Comment by vbatoufflet** [comment]
A basic support has been shipped in 20a61e0f495e188c88fb234cc23796372965cb32.

Pressing `Shift` key when toggling a series in the legend will only display this series.
