### ISSUE TITLE
embed graphs in other web page

### ISSUE THREAD

**Issue by lola27** [facette/facette#268]
Hi,

Is there any API or methods we can use to embed the graphs in other web page? Thanks

**Comment by falzm** [comment]
Hi @lola27 

Yes it's possible using the 'link' icon on a graph's buttons:

<img width="1093" alt="screen shot 2015-11-14 at 15 25 18" src="https://cloud.githubusercontent.com/assets/1122379/11163999/6efa8452-8ae4-11e5-8896-b702cca32c5d.png">

**Comment by lola27** [comment]
thanks
