### ISSUE TITLE
Creating a metric group based graph

### ISSUE THREAD

**Issue by gy0kuro** [facette/facette#269]
When adding a graph, from a metric groups, it does not preserve the order of items and some items are lost on the way (28 in the Metric Group and 21 in the graph created).

**Comment by vbatoufflet** [comment]
Hi,

I'm not sure to understand the issue correctly. Can you provide us with some steps to reproduce the pronlem?

**Comment by gy0kuro** [comment]
Hello Vincent,

The goal is to create a IN/OUT graph for ESX hosts.

The steps :
1) create a metric group with all .rx et .tx (all .rx in the UP area, all .tx in the DOWN area - )
![capture du 2015-11-16 14 05 54](https://cloud.githubusercontent.com/assets/11042104/11182985/5552dcac-8c6f-11e5-899a-3563bddbf21a.png)

2) create a graph for one ESX host with the metric group
![capture du 2015-11-16 14 07 12](https://cloud.githubusercontent.com/assets/11042104/11183154/747789ce-8c70-11e5-90e1-031a7ee641f9.png)

3) expand the source to check order & number of sources
![capture du 2015-11-16 14 07 47](https://cloud.githubusercontent.com/assets/11042104/11183170/94cf2560-8c70-11e5-991e-ee36d464d38b.png)

4) graph i want to create (tested & functional)
![last](https://cloud.githubusercontent.com/assets/11042104/11183181/a3ab19d6-8c70-11e5-8f38-6cdd734c8c23.png)

Sorry for bad english -__-
3) result (as expected)

**Comment by vbatoufflet** [comment]
Indeed, I did reproduce the order loss. But not the missing items.

Just for you to know, if you expand the series, you lose the reference to the groups. All the series will be saved as individual series. So if you modify the groups, it won't reflect any change on the graphs.

I will take a look at preserving the items order.

**Comment by gy0kuro** [comment]
Hello Vincent,

OK thanks for the tip!
