### ISSUE TITLE
Cloning a graph

### ISSUE THREAD

**Issue by gy0kuro** [facette/facette#270]
I've a lot of ESXi hosts to plot & i decided to clone an IN/OUT (and complicated) graph.

Two ways for that, CLI or Web-GUI :
- for the first, a failed (i located the json file, modify, check the user's rights) : "Failed to load" "graph" in the preview ;
- via web interface, when you clone a graph and update the data sources (updating host/source) it shows a red message (An error occurred while performing operation studs) and a "Failed to load" "graph" in the preview.

Am i doing something wrong ?

**Comment by vbatoufflet** [comment]
Hi Thomas,

Do you have any specific error message in the logs when the red message triggers?

**Comment by gy0kuro** [comment]
OK, sorry, my bad, i forgot to watch the log : this is a config mistake, a portgroup isn't present in that ESX... the log said :
---
2015/11/16 14:54:31 WARNING: server: unknown metric `snmp.if_octets-YYY.rx' for source `esx-XXX' in origin `collectd'
2015/11/16 14:54:31 WARNING: server: unknown metric `snmp.if_octets-YYY.tx' for source `esx-XXX' in origin `collectd'
2015/11/16 14:54:31 ERROR: server: unable to make plots response: unable to find plots for `snmp.if_octets-YYY.rx' series
---

I remove the data source from the graph & it works now.
