### ISSUE TITLE
Renaming of metric groups does break all graphs using this metric group

### ISSUE THREAD

**Issue by TomGudman** [facette/facette#272]
Hi,

Posting this on behalf of a colleague.
## How to reproduce this problem:
- Created a metric group (match type: glob) (i.e. "disk._.ops._") and
  give it a name (i.e "MG-IO")
- Create a graph using the metric group "MG-IO". Give it a name (i.e.
  "hostA-diskIO')
- Look at your new graph. Everything looks as expected.
- Back in Metric Groups, edit your metric group ("MG-IO"), don't change
  the items, click next, change the name (i.e. from "MG-IO" to
  "MG-IO-changed")
- Find your graph ("hostA-diskIO"), Go to Graph, No data is shown. Even
  after using the "Refresh Graph" button
## How to make it work again:
- In Metric Groups, change the name back to it's original name (i.e.
  from "MG-IO-changed" to "MG-IO")
- Look at the graph ("hostA-diskIO") again. It's now working again.
## Conclusion:

When creating a graph using metric groups, it get's linked not via it's
ID (which every metric group seems to have?) but via it's name.
## Is this intended?

Are there any plans to link graphs to metric groups via their ID in a
future release?
## Build Information:

Version:  0.4.0dev
Build Date:   2015-07-21
Compiler:   gc (go1.4.2)

**Comment by vbatoufflet** [comment]
Hi Tom,

Indeed, the way it was designed didn't took this operation into account.

We will work on that and try to find a proper way to avoid this kind of breakage.

**Comment by TomGudman** [comment]
No worries. Thanks

**Comment by falzm** [comment]
Fixed in branch [0.4-alpha](https://github.com/facette/facette/tree/0.4-alpha).
