### ISSUE TITLE
Incorrectly escaped quotes from graphite connector

### ISSUE THREAD

**Issue by tmack0** [facette/facette#274]
See Issue #84 
Same problem, but with the alias name. The src supplies \" as the escape instead of %22. Some browsers/proxies/http servers compensate for this by automagically url-escaping. Graphite itself is less friendly.

Per my graphite access logs: 

"GET /render?format=json&target=alias(collectd.graphite.interface-eth0.if_packets.rx, \"series0\")&target=alias(collectd.graphite.load.load.shortterm, \"series1\")&target=alias(collectd.graphite.interface-eth0.if_packets.tx, \"series2\")&from=-3600s&until=-0s HTTP/1.1"

should be

"GET //render?format=json&target=alias(collectd.graphite.interface-eth0.if_packets.rx,%20\%22series0\%22)&target=alias(collectd.graphite.load.load.shortterm,%20\%22series1\%22)&target=alias(collectd.graphite.interface-eth0.if_packets.tx,%20\%22series2\%22)&from=-3600s&until=-0s HTTP/1.1"

the \%22 might need to be just %22, will test and submit a patch/pull req shortly. 

File:Line in src in question is pkg/connector/graphite.go:233

**Comment by vbatoufflet** [comment]
No longer relevant in [0.4-alpha](https://github.com/facette/facette/tree/0.4-alpha) as aliases are longer transmitted to Graphite.
