### ISSUE TITLE
Debian control file out of date

### ISSUE THREAD

**Issue by tmack0** [facette/facette#275]
Trying to build .deb from current 0.3 src, build fails due to unmet deps not listed or incorrect in control file

1. The required version of golang-go is too old, main Wheezy golang-go package lacks time.Round method and will fail with a message referencing that. Need to install golang-go_2:1.3.3 from backports for Wheezy (INSTALL says golang-go 1.2 or newer).
2. There is no dependency on nodejs itself, only a few extras for it. Per INSTALL nodejs-legacy is needed, which for Wheezy requires the backport version of nodejs. Currently, Wheezy backports is OLDER than mainstream (0.12.1-1 vs 0.10.29~dfsg-1~bpo70+1). Had to remove the mainstream nodejs and install the backport branch of it (and then nodejs-legacy and the others), effectively downgrading nodejs.

will have a pull req. shortly

**Comment by vbatoufflet** [comment]
The referenced PR has been merged.
