### ISSUE TITLE
Creating a graph with attributes / wildcards is not possible

### ISSUE THREAD

**Issue by konstantinj** [facette/facette#280]
Hi,

just installed facette as a docker container linked to my collectd container. When I try to create a new graph I can select collectd as my origin but I can only select my source directly and I cannot use an attribute like it is described here: https://blog.facette.io/2015/03/23/dive-into-facette-graph-templates/
Also at the metrics input I can only choose absolute metrics and cant use a wildcard like load.*. It always autocompletes to the first entry in the suggestion list.

**Comment by falzm** [comment]
Hi @konstantinj, what version do you run?

**Comment by konstantinj** [comment]
https://hub.docker.com/r/facette/facette/tags/ latest. Should I directly use 0.3.0? Why is this so much smaller?

**Comment by falzm** [comment]
Usually the `latest` tag is stable. I'm not exactly sure to understand your issue, though. If you start facette with logging level `debug`, can you check the logs to verify the facette instance can actually access your collectd RRD files?

**Comment by konstantinj** [comment]
Everything is working fine. I've created some graphs. It's just that when I try to use wildcards like load.* like it is described in this blogpost (https://blog.facette.io/2015/03/23/dive-into-facette-graph-templates/) I don't get a graph. I'll check what debug says in that case. But at least it's weird that the autosuggest automatically completes to the first entry in the list.

**Comment by konstantinj** [comment]
Tried the 0.3.0 image and built it from sources. Still the same issue. Logfile says
> WARNING: server: unknown source `{{ .source }}' for origin `collectd'
Accourding to the blogpost that should actually work. What am I doing wrong?

**Comment by falzm** [comment]
Is your provider actually named "`collectd`"?

**Comment by konstantinj** [comment]
Yes. I just used the example configs to be sure that's not the problem. The UI is listing collect as origin and my single configured host "localhost". I just can't use attributes or wildcards for metrics.

**Comment by vbatoufflet** [comment]
Hi @konstantinj,

Ok, I think I understand the issue here.

You try to use the wildcard directly in the graph creation page. Looking at the screenshot present in the blog article, it surely can be misleading but you can't use wildcards here. They are only used for auto-completion purpose.

If you want to have all metrics matching `memory.*` glob pattern, you will have to create a metric group for that and use it in the graph creation page.

**Comment by remss** [comment]
Having the wildcard could be a nice feature to allow template graph for `cpu.*.idle` that will graph all CPUs whatever the number of CPU is.

**Comment by vbatoufflet** [comment]
Hi @remss,

You should definitively use a metric group for that :)
