### ISSUE TITLE
Zooming render empty zones

### ISSUE THREAD

**Issue by francois2metz** [facette/facette#281]
Hi,

I'm using facette with the rrd provider.

When displaying the overall graph (ie, not zoomed) I can see some value (400 or more).
But when zooming, parts of the chart is not rendered. See sceenshots below. (screenshots were cropped to only show relevant data: result and axis)

![facet1-unzoom](https://cloud.githubusercontent.com/assets/86659/11814532/8731e92c-a347-11e5-9026-3337196116d2.png)

![facet1-zoom-empty](https://cloud.githubusercontent.com/assets/86659/11814533/87343d12-a347-11e5-95cf-7fc08413d44e.png)

I looked at the api response. I have some `null` values in the response that match the corresponding timestamp.

**Comment by vbatoufflet** [comment]
Hi @francois2metz,

Thanks for your feedback.

It seems that there is some issue in our series normalization process resulting in `NaN` values. We will take a closer look at it.

**Comment by vbatoufflet** [comment]
Normalization has been reworked in [0.4-alpha](https://github.com/facette/facette/tree/0.4-alpha).
