### ISSUE TITLE
Binaries are dynamically linked

### ISSUE THREAD

**Issue by TomHetmer** [facette/facette#283]
The binaries are dynamically linked which limits their use. Applies both to armhf & amd64.

```
➜  bin  file facette
facette: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, BuildID[sha1]=1276b299c53034ff9f97d2c1d5335e29451a78d9, not stripped
```

Oops, we're not gonna have luck with that interpreter on my system.
```
➜  bin  ls /lib/ld-*
/lib/ld-musl-armhf.so.1
```

Adding libc6-compat does get it to work (+ rrdtool), so that's a non-issue now.

But I have two other Go apps installed and they're both statically linked, so I'm curious what's the proper method to publish go binaries.
Was this a conscious decision or some bug like this one https://groups.google.com/forum/#!topic/golang-nuts/Rw89bnhPBUI ?

thx.

**Comment by TomHetmer** [comment]
I ran into a bug with ziutek/rrd crashing the go app with some stack error. It was probably compiled against a different rrdtool version, so the binaries definitely need to be static at least on my server.

I've recompiled from source and now it's working fine.

**Comment by vbatoufflet** [comment]
Hi @TomHetmer,

We made some tests at the time but we didn't manage to make the binary fully static due to the usage of packages relying on cgo. For example the `rrd` package.

**Comment by TomHetmer** [comment]
I see

From looking at http://dominik.honnef.co/posts/2015/06/statically_compiled_go_programs__always__even_with_cgo__using_musl/

It would mean linking against musl and recompiling whole librrd w/ musl (or doing this on a distro w/ musl as default).
So i'm closing this unless you want to do that :smile:
