### ISSUE TITLE
rrd datasources vs facette metrics

### ISSUE THREAD

**Issue by enp** [facette/facette#286]
For every datasource in any rrd file (ping/value for example) I see 3 facette metrics (ping/value/{min,max,average}). Why I see them?

**Comment by falzm** [comment]
Hi

This is because Facette generates one metric entry per "RRA" in a RRDtool file. You can use the provider filters to exclude the metrics you don't want: http://docs.facette.io/configuration/filters/

**Comment by falzm** [comment]
Example provider using filters:

```
{
	"connector": {
		"type": "rrd",
		"path": "/var/lib/collectd/rrd",
		"pattern": "(?P<source>[^/]+)/(?P<metric>.+).rrd"
	 },

    "filters": [
        { "action": "sieve", "target": "metric", "pattern": "/average$" },
        { "action": "rewrite", "target": "metric", "pattern": "/average$", "into": "" }
    ]
}
```

**Comment by enp** [comment]
Thanks, I did not know about {min,max,average} RRA before.
