### ISSUE TITLE
nginx configuration for /facette sublocation

### ISSUE THREAD

**Issue by enp** [facette/facette#287]
Is it possible to configure nginx to proxy all requests for /facette sublocation to running facette instance at http://localhost:12003? My question looks like nginx-specific, but I did not know if it is possible at all, because html code returned from http://localhost:12003 will contain all urls without /facette prefix. So, on which side (nginx or facette) this must be configured?

**Comment by vbatoufflet** [comment]
Hi @enp,

You should take a look at the `url_prefix` parameter in the Facette global configuration: http://docs.facette.io/configuration/.

You should define it at `/facette`, make this prefix prepended to all URLs in the application.

**Comment by enp** [comment]
Thanks, it works.

**Comment by vbatoufflet** [comment]
You're welcome :)
