### ISSUE TITLE
Non-unique names for graphs in collections tree

### ISSUE THREAD

**Issue by enp** [facette/facette#288]
I have some source groups for which I need to show the same metrics. I can create suitable graphs for every source group, which differs only by source (maybe it will be possible to use templates for this in future?), but now I need to have at least the same names for graphs, so it must looks like:

```
NS servers
   CPU
   Memory
HTTP servers
   CPU
   Memory
```

Graphs names names must be unique, so I can do only this now:

```
NS servers
   NS CPU
   NS Memory
HTTP servers
   HTTP CPU
   HTTP Memory
```

Is it possible to fix it? Maybe another graph parameter for collections tree only?

**Comment by falzm** [comment]
Hi @enp 

If I understand your need correctly, you can reference a source group as a template entry with the `group:` prefix, e.g. if your source group is named `NS servers` then instanciate a graph template and fill the template attribute such as `group:NS servers`.

Let us know if this solves your problem.

**Comment by enp** [comment]
No, I need two collections (NS servers and HTTP servers) with the same graphs for every collection (CPU and Memory). I can create two source groups (ns and http with servers ns0 and ns1 in first group and http0 and http1 in second group). Next I can create two graphs for every source group, so it will be four graphs. But I need to give them a unique names, I can't have two graphs with name CPU for example (even if them will be in different collections). It will be good to have another name to show it in collection graph list on left panel - which will not unique.

Templates is another question, because it is not documented well now - see https://github.com/facette/facette/issues/280. So, I do not understand how to create template and what is it. I can use source group or metric group to show more than one lines/areas on one graph, but the result is one graph, not graph template.

**Comment by enp** [comment]
Sorry, graph title solves my main problem. So, only templates needs additional explanation.

**Comment by falzm** [comment]
Hey @enpm, could you have a look at the 0.4.x version [released recently](https://blog.facette.io/2017/06/21/facette-0-4-0alpha1-released-2/)? Looks like the _collection templates_ introduced in this version can solve your problem: you can create graph templates that can use a source group as template attribute – for example in the graph _title_ –, then create a collection template referencing the graph templates created previously. Finally, instantiate 2 different collections using the collection template, providing for each one the source group ID corresponding to your "NS servers" and your "HTTP servers" as template attribute.
