### ISSUE TITLE
Prevent graph toolbar overlap with series tooltips

### ISSUE THREAD

**Issue by falzm** [facette/facette#289]
Could it be possible to prevent graph toolbar to overlap with series tooltips? Cometimes it's not possible to see values if they are too close to the graph toolbar:

![screen shot 2016-01-18 at 09 56 50](https://cloud.githubusercontent.com/assets/1122379/12387047/13f0f078-bdca-11e5-81b7-3a2c30871a60.png)

**Comment by vbatoufflet** [comment]
I guess we can figure a way to hide the toolbar when the tooltip is displayed.

**Comment by vbatoufflet** [comment]
Fixed in [0.4-alpha](https://github.com/facette/facette/tree/0.4-alpha).
