### ISSUE TITLE
How to change default time range?

### ISSUE THREAD

**Issue by enp** [facette/facette#290]
Hi,

Is it possible to change default time range for all graphs from 1h to 1d?

**Comment by njh** [comment]
+1 Would love to see this.

Tried putting #range-1d on the end of the URL but that didn't work.

**Comment by vbatoufflet** [comment]
@enp, do you want it changed globally?

If yes, we can mange to add a setting for that in the configuration file, like `default_range`.

**Comment by enp** [comment]
setting will be better than hardcoding

**Comment by njh** [comment]
I would be happy with setting it globally.

**Comment by xSmurf** [comment]
It would be great too if the front end would save the selected date range and refresh rate in the local storage to that is persist page changes.
