### ISSUE TITLE
questioN regarding faceted calssification

### ISSUE THREAD

**Issue by joeblew99** [facette/facette#292]
i know this does metrics, but under the hood does it essentially do faceted classification?

**Comment by falzm** [comment]
Hi

Sorry, I don't understand your question...

**Comment by joeblew99** [comment]
Faceted classification is a type on indexing, and allows thing like how Amazon search works with th facets on the left side.

These guys explain it better than me:
http://clojureelasticsearch.info/articles/facets.html

**Comment by falzm** [comment]
Facette is really only a time series front-end, it fetches datapoints from storage backends (RRDtool, Graphite etc.) and renders them on charts... It has nothing to do with search :)

**Comment by joeblew99** [comment]
Thanks.

Is this code base usable.
I have a data lake of data and am looking for a way to visualise it, but
also run computations on it to get metrics out.
