### ISSUE TITLE
wrong `cp` flags on NetBSD and probably others

### ISSUE THREAD

**Issue by iMilnb** [facette/facette#295]
```
build: Copying template files...
cp: unknown option -- -
usage: cp [-R [-H | -L | -P]] [-f | -i] [-alNpv] src target
       cp [-R [-H | -L | -P]] [-f | -i] [-alNpv] src1 ... srcN directory
result: fail
Makefile:306: recipe for target 'build/facette-netbsd-amd64/template' failed
gmake: *** [build/facette-netbsd-amd64/template] Error 1
```

Seems like you should test the following on "Linux vs everything else" :)

```
ifeq ($(UNAME), Darwin)
       $(eval COPY_CMD=rsync -rR)
else
       $(eval COPY_CMD=cp -r --parents)
endif
```

**Comment by emaste** [comment]
(Unsurprisingly) the same issue is present on FreeBSD

**Comment by falzm** [comment]
Could you by any chance submit a pull request with a patch working on NetBSD/FreeBSD? We can't easily test those by ourselves...

**Comment by emaste** [comment]
What is $(UNAME) on Linux systems?

**Comment by falzm** [comment]
`Linux`

**Comment by emaste** [comment]
Hmm, it looks like this was already addressed in cd94d9ca

**Comment by falzm** [comment]
My bad, didn't look it through. @iMilnb can you confirm?

**Comment by vbatoufflet** [comment]
Please reopen if still relevant in branch [0.4-alpha](https://github.com/facette/facette/tree/0.4-alpha).
