### ISSUE TITLE
License issue - Highcharts library is not open source and not free.

### ISSUE THREAD

**Issue by roman-io** [facette/facette#300]
I like Facette a lot. I have spent a lot of time installing it and configuring all the charts. After that, I discovered that Facette uses proprietary software, the Highchart library, which costs $150 per domain. Don't you think that users should be aware of that before the installation?

**Comment by vbatoufflet** [comment]
Hi @roman-io,

You are right. We will have to let user know that Highcharts is not open-source and licensed under the terms of [CC BY-NC 3.0](http://creativecommons.org/licenses/by-nc/3.0/) for personal and non-profit usage. Sorry for the lack of information.

For the record, the next major release being developed right now has dropped Highcharts for D3.

**Comment by vbatoufflet** [comment]
Addressed in [0.4-alpha](https://github.com/facette/facette/tree/0.4-alpha).
