### ISSUE TITLE
ERROR: server: don't understand 'series0-def0'

### ISSUE THREAD

**Issue by raphirm** [facette/facette#301]
HI Guys, I don't know how i can go further. 

When i want to plot the rrd data, i get the following error from RRD:
2016/06/20 19:27:17 ERROR: server: don't understand 'series0-def0'

What did i configure wrong? All facette configurations are more or less standard from the manual. Can someone help here?

Thanks and Regards
Raphael

**Comment by vbatoufflet** [comment]
Hi @raphirm,

Which version of RRDtool are you using?

**Comment by ramsingla** [comment]
This is also happening with me. RRDtool 1.5.5 here.

**Comment by ramsingla** [comment]
Compiling the build from the master solves this issue at my end.
