### ISSUE TITLE
Bytes are not metric and seconds aren't fixed.

### ISSUE THREAD

**Issue by xSmurf** [facette/facette#302]
Hello, are there any plans to add IEC bytes (kibi/mibi/gibi/byte) and (second based) time to the data "type"? Neither of those represent well under either fixed of metric.

**Comment by vbatoufflet** [comment]
Hi @xSmurf,

The next release will have three types of units for graphs:
 * `fixed` which basically doesn't do anything
 * `metric` which uses the SI prefixes
 * `binary` which uses the IEC

We can certainly add a `duration` one too.

**Comment by xSmurf** [comment]
Fantastic!

I'd love to see a duration unit indeed, if it's not so much trouble. I'm using the scaling method to display uptimes in days, more practical than seconds, but still not ideal.

Merci :)

**Comment by vbatoufflet** [comment]
Implemented in [0.4-alpha](https://github.com/facette/facette/tree/0.4-alpha).
