### ISSUE TITLE
Unable to save graph

### ISSUE THREAD

**Issue by remss** [facette/facette#303]
- facette_0.3.0-1.jessie_amd64.deb
- provider rdd as the doc does
- create a graph and save

=> got alert "unsable to save graph"
=> refresh page : the graph is here
=> restart facette daemon then refresh page : the the graph is gone

**Comment by vbatoufflet** [comment]
Hi @remss,

Do you have any specific error in the logs?

**Comment by remss** [comment]
Thanks I see my problem, there was permission issue on `/var/lib/facette/graphs/46/1f/461f115d-1e0f-4f6d-7812-87a195b3ca70.json `
I started the facette process by hand (as "root") the first time like the documation says.
But now I use the init script that spawn facette process with the "facette" user ...
Problem solved with a `chown facette. -R /var/lib/facette`
Documentation may be improved for those using the debian package ?
