### ISSUE TITLE
api filter "templates" doesn't seems to be working

### ISSUE THREAD

**Issue by thierry-f-78** [facette/facette#309]
Hi,

I use this shell command for the extraction of my graph templates:

`curl -s 'http://192.168.1.1/api/v1/library/graphs/?templates=1'`

and this command returns all the graphs. Do I use the right syntax ? or maybe the filter doesn't work ?

In other way, I dont see recent updates on the 'go' code of this project. It is still alive ?

Thierry

**Comment by vbatoufflet** [comment]
Hi @thierry-f-78,

I just looked at the documentation and it seems that it's out of date regarding the way to display the templates.

The right call would be `curl -s http://192.168.1.1/api/v1/library/graphs/?type=template`. Sorry for that.

Regarding your second point, the project is still alive, but a major code rewrite has been done but not yet made public. I will try to publish it on Github in a separate branch this week-end 🙂

**Comment by thierry-f-78** [comment]
Thank, thats run ! Great news for the new version.

**Comment by thierry-f-78** [comment]
ps: I just discovered the project and I like it:
 - no database !
 - easy to install
 - customisable and templatisable
 - simple api
 - configuration accessible with files
thank for this software !

**Comment by vbatoufflet** [comment]
Hi @thierry-f-78,

Thank you for your kind words.

But I must admit that the next release will use a database though. It will improve the overall performance and allow users to run multiple instances of Facette using the same database (for failover purpose) if they want to.

Nevertheless, it will use a **SQLite database by default** and will not require any specific setup.
