### ISSUE TITLE
Graph created but not shown in 0.4

### ISSUE THREAD

**Issue by clemensg** [facette/facette#320]
Hi,

if a graph is created in the admin panel, the operation succeeds (and an entry is created in the SQLite database), but the graph is not visible in the list.
Interestingly, if I want to add the invisible graph to a collection, the autocompletion of the graph field does suggest its name and I can add it, however if I then add the collection, it is not visible either.

I am attaching the library dump for you to reproduce it:
[facette-201705011736.tar.gz](https://github.com/facette/facette/files/968202/facette-201705011736.tar.gz)

**Comment by vbatoufflet** [comment]
Hi,

It seems to impact SQLite only and to be related to handling of boolean values when executing queries using this driver.

I'll try to find a fix for this quickly.

**Comment by vbatoufflet** [comment]
Fixed in 459b53bcd19fe4e1d8720e7a3e88b1e0f2948148.

**Comment by vbatoufflet** [comment]
I did find what caused SQLite to behave like this. You should be able to list your items now, but you'll have to delete the existing SQLite database file and reimport your dump.

**Comment by clemensg** [comment]
Thanks! 👍
