### ISSUE TITLE
Missing metrics with collectd

### ISSUE THREAD

**Issue by jessicah** [facette/facette#332]
It seems facette is only providing a small number of metrics with collectd. In Metrics list, it only lists 207, whilst I have 889 rrd files in /var/lib/collectd.

Also not sure why the metric names don't match the rrd filenames.

I have a match pattern of `(?P<source>([^/]+))/(?P<metric>([^.]+)).rrd`, but I don't see any metrics that have names matching the filenames at all. Also, files are like `/var/lib/collectd/vmrepo.haiku-os.org/apache/apache_idle_workers.rrd`, but the sub-directory name doesn't show up in the metrics.

I just get things like `baron.haiku-os.org/count/average`. I don't have a clue what that's supposed to be.

Running the facette/facette docker container.

**Comment by vbatoufflet** [comment]
Hi @jessicah,

Do the logs display something regarding any potential pattern matching issue? Have you tried to set `log_level` to `debug`?

**Comment by jessicah** [comment]
Snapshot of output is https://gist.github.com/jessicah/d8c5fd68146d36d9c7c5b533e9571f8d

I see a lot of `Metric: "baron.haiku-os.org/value/{average/min/max}"` being added. I'm guessing that because it's not including the actual filename portion for the metric, that it's causing a metric tonne of duplicates?

**Comment by jessicah** [comment]
Seems my regex wasn't matching correctly :( perhaps it should generate errors when either group results in an empty string?

Using `(?P<source>[^/]+)(?P<metric>.*)\.rrd` got it working.

**Comment by vbatoufflet** [comment]
Indeed, it might be useful to generate an error in this case. I'll open an issue to track this improvement.
