### ISSUE TITLE
panic: interface conversion: interface {} is map[string]interface {}, not map[interface {}]interface {}

### ISSUE THREAD

**Issue by avoine** [facette/facette#335]
I've got this error while trying to configure an influxdb provider using the mapping method.
I'm pretty sure I miss something obvious but facette won't starts anymore.
I know I'm new to this but could you show me an example of what would be the configuration
for a typical database like the ones in:

https://docs.influxdata.com/influxdb/v1.3/introduction/getting_started/

Thanks.

**Comment by vbatoufflet** [comment]
Hi @avoine,

Could you please give me the version of Facette you are using and full stack trace of the panic output?

If the configuration is invalid, Facette shouldn't crash 😄

**Comment by vbatoufflet** [comment]
Should be fixed by a8e1c7f53cf1f46e9a7e6c918db4b9c6d49f1deb.
