### ISSUE TITLE
Aggregating different sources

### ISSUE THREAD

**Issue by gokarslan** [facette/facette#337]
I want to aggregate metrics of a source group, but when use source groups for metrics, it puts data from different sources separately.
 
For example, consider I have source group `glob:node*` and I have two sources `node-1` and `node-2`, and for each of them I have metric `cpu.idle`. What I want to show on graph is a `cpu.idle` metric which is aggregation (preferably average) of `node-1.cpu-idle` and `node-2.cpu-idle`. But when I use source groups for that, it shows `node-1.cpu-idle` and `node-2.cpu-idle` separately.

Does Facette support this? If not, do you have plans to support it?

**Comment by vbatoufflet** [comment]
Hi @gokarslan,

You can perform some operations on series when grouped or when source/metric groups are present.

You have to click on the “cog” icon to do so and select ”Sum” or ”Average” as operation:

![graphs-operation_average](https://user-images.githubusercontent.com/598433/31981676-21018aec-b955-11e7-9fa5-b76a76baaeb0.gif)

Let me know if it answers your question.

**Comment by gokarslan** [comment]
Hi @vbatoufflet,

Thank you very much for your answer, it answers my question for single metric with source group.  Another thing I'm curious about is what if I have a metric group and source group and I want to sum metrics on metric group for per source and then take average of them.

For example, if I have a metric group M with metrics M1, M2 and source group S with sources S1 and S2, what I want to calculate is first M1+M2 for each source (S1, S2) then taking average of those sum. (i.e. if my resulting field is M_R; let M_S1 = M1+ M2 (source S1) and M_S2=M1+M2 (source S2) then M_R = (M_S1 + M_S2)/2)

Is this possible?

**Comment by vbatoufflet** [comment]
That's not possible given the way it works today. All you'll we have is a resulting ”big” average or sum of all matching source/metric couples.
