### ISSUE TITLE
Summation of metric groups

### ISSUE THREAD

**Issue by gokarslan** [facette/facette#338]
Hi,

I have a scenario like this: 
I have a metric group G which matches metrices M1, M2, M3 and M4 and I have source group SG which matches sources S1 and S2. Metrices M1, M2 are common between S1 and S2, M3 is only from S1 and M4 is only from S2. I want to create a graph with source group: SG, and metric group: G and I'm using sum as aggregation method. However, since M3 doesn't exist for S2 and M4 doesn't exist for S1; it doesn't work (in logs facette says unable to find series metric). How I can assume metrices with null values as zero when I aggregate them? 

I've already tried `Set null values to zero` option but it doesn't work either.

**Comment by vbatoufflet** [comment]
Hi @gokarslan,

Which version of Facette are you testing it on? 0.3.x or 0.4.x?

**Comment by vbatoufflet** [comment]
Hi @gokarslan,

Which version of Facette do you use? 0.4.0rc2 release or a build from `master`?

I'll take a look at it to see if I can reproduce the issue.

**Comment by gokarslan** [comment]
I’m building from master.

**Comment by gokarslan** [comment]
Hi @vbatoufflet,

Is there any news on that issue?

**Comment by vbatoufflet** [comment]
Hi @gokarslan, 

After few tests I did reproduce your issue.

While I was able to fix the normalization error preventing the summation (see b2ddcd0ca0bf29a3bb40a487e289a726accdbf0b), the warnings will remain in the logs and will need some additional work.

You should be able to sum those series now. Don't hesitate to reopen if I forgot something.
