### ISSUE TITLE
Invalid format for BUILD_TAGS specified in web site

### ISSUE THREAD

**Issue by vvromanov** [facette/facette#339]
Page https://docs.facette.io/latest/installing/
states 

> build a version that suits to specific needs set BUILD_TAGS variable with a list a revelant tags, separated by commas.

You must use space instead of comma. For sample 
> make BUILD_TAGS="builtin_assets disable_connector_influxdb"

**Comment by vvromanov** [comment]
Also disable_driver_mysql disable_driver_pgsql must be used instead of disable_backend_mysql disable_backend_pgsql

**Comment by vbatoufflet** [comment]
Issue duplicated in the associated repository, see https://github.com/facette/facette-docs/issues/19.
