### ISSUE TITLE
Authentication/Access control

### ISSUE THREAD

**Issue by Tomasu** [facette/facette#341]
Does facette have support for allowing multiple users with different privilege levels? 

Most specifically, I'm interested in guest access that can't access the admin page.

I realise i could probably put facette behind a proxy that does http auth, and provide a basic page that embeds the graphs. Though that's a bit of a management headache.

**Comment by falzm** [comment]
Hi @Tomasu 

Sorry but at the moment Facette doesn't provide any user management system, so basically yes the only option is to defer access control to an upstream reverse-proxy.

**Comment by falzm** [comment]
Closing this issue as a dedicated feature request issue (#352) has been created.
