### ISSUE TITLE
No URL prefix in 0.4

### ISSUE THREAD

**Issue by jollyroger** [facette/facette#342]
After migrating to 0.4 version I have found that URL prefix parameter has been disappeared. This regression makes impossible to run facette behind any other webserver (I'm using nginx to serve static files and proxy other requests to the facette backend otherwise).

**Comment by vbatoufflet** [comment]
Hi @jollyroger,

The `url_prefix` setting has been renamed `root_path`, see https://raw.githubusercontent.com/facette/facette/master/docs/examples/facette.yaml example configuration for an example.

I'll add this setting to the documentation. Sorry about that 🙂

**Comment by jollyroger** [comment]
Thank you for the quick response! I have already succeeded to hardcode this in index.html but your solution is what I was really looking for!

Here is a simple Nginx config for you to include in the docs to describe this use case:

```nginx
location /facette {
    root /usr/share;
    try_files $uri @facette;
}

location @facette {
    include proxy_params;
    proxy_pass http://localhost:12003;
}
```

**Comment by vbatoufflet** [comment]
The documentation has been updated: https://docs.facette.io/latest/configuration/.
