### ISSUE TITLE
Aggregation function over metric group in a graph template

### ISSUE THREAD

**Issue by jollyroger** [facette/facette#343]
Hello! Thank you for adding collection templates, that saved me a lot of time! However there are still ways to improve! 

Currently I can group metrics in a graph only if they are not templated. In this case metric group can be expanded and all metrics can be arranged into groups one by one and aggregation function can be applied for such groups. I'm looking for a bit different approach:

 * create metric group that consists of multiple glob/regex patterns (like `cpu.*.wait`, `cpu.*.user` etc.)
 * allow for metric group to be expanded as grouped metrics during graph template creation based on its glob/regex pattern (e.g each group has one "virtual" source that is a glob/regex expression)
 * apply aggregation and consolidation function to these grouped metrics during template creation

Thanks!

**Comment by vbatoufflet** [comment]
Hi @jollyroger,

If you create metric groups to use in templates (for example using `{{ .source }}` as source) then, without expanding, chose a aggregation/consolidation for them. Isn't the result what your are looking for?

Maybe I missed something, just let me know.

**Comment by jollyroger** [comment]
Hi @vbatoufflet, If I understand you right, I just need to create multiple metric groups with a single glob pattern for each group (like one group with `glob: cpu.*.user`, another one with `glob: cpu.*.wait` and so on). Apparently what I did wrong is that I did a single metric group with all these glob patterns included instead of what you described. I thought it could be possible to (partially) expand metric group and apply aggregation to glob patterns.

Using multiple metric groups should work as expected. Thank you!

As a side note, could you please clarify what is the difference between aggregation and consolidation functions (i'm using collectd as a single provider currently)?

**Comment by jollyroger** [comment]
I'm sorry, I was to fast to reply. I have tried your approach and unfortunately I cannot apply aggregation/consolidation functions to a metric group when there is a template variable (llike `{{ .source }}`). Otoh, when I add metric groups with defined source, I can see all metrics inside and can apply aggregation/consolidation function to the metric group itself.

![selection_001](https://user-images.githubusercontent.com/96645/33260616-12cd770a-d369-11e7-8d5e-b6034371f6b4.png)

**Comment by vbatoufflet** [comment]
You should have access to the aggregation options even using `{{ .source }}` as source.

![screen shot 2017-11-29 at 14 04 00](https://user-images.githubusercontent.com/598433/33376540-59c2978e-d50e-11e7-8261-78d69eafff67.png)

Or am I missing something?

**Comment by jollyroger** [comment]
Unfortunately this is not what I see:

![selection_001](https://user-images.githubusercontent.com/96645/33376992-78223842-d518-11e7-9d2a-71c95ef82ff6.png)

I have a single Glob match in `group:metric_cpu_system`, it is `glob: cpu.*.system`

Additional information: Facette version 0.4.0rc2 (Debian jessie, deb downloaded from)

**Comment by vbatoufflet** [comment]
My bad, I guess I forgot to cherry-pick this change in the 0.4 branch.

As the latest RC was released quite some time ago without huge bug reports, I will release a final version soon which should include this change.

**Comment by jollyroger** [comment]
Thank you, will wait for updates!

**Comment by vbatoufflet** [comment]
You should be able to use this now that the [0.4.0](https://github.com/facette/facette/releases/tag/0.4.0) version has been released.

**Comment by jollyroger** [comment]
Hi!

Unfortunately nothing changed. I restarted facette and cleared the cache to be sure there was no issue but still there was no aggregation/consolidation fields in the interface.

**Comment by jollyroger** [comment]
Sorry for the late reply. 

For all others who did not spot this feature at first sight: when a new graph is created using metric groups, by default the second configuration tab is opened:

![2018-03-04-124039_821x319_scrot](https://user-images.githubusercontent.com/96645/36944665-d84af584-1fa9-11e8-8c0d-1f44f9dd0128.png)

To set the aggregation/consolidation features you have to switch to the first configuration tab. 

![2018-03-04-124100_818x583_scrot](https://user-images.githubusercontent.com/96645/36944666-d8699750-1fa9-11e8-948e-dbb08d88895a.png)

This is the difference in behaviour for the configuration widow that confused me.
