### ISSUE TITLE
How to define origins, sources, metrics?

### ISSUE THREAD

**Issue by rb07** [facette/facette#344]
Hi,

After setting up facette, reading all the documentation, I can't find how to add the above.

I see them in the browse page, but selecting any of these 3 doesn't show the add '+' like the one in collections, graphs, etc.

Reading old documentation I see there was a "provider settings" file, which should have the information I'm trying to add.

Just defining the information on the graphs doesn't seem to have any effect: no data is actually plotted, nothing is added to the origins/sources/metrics sections... and I'm not even sure what the format should be, i.e. what's the relation btw the actual file path (in my case collectd + rrd files), and the values used (it makes more sense to put the detail in the configuration, not the name).

The only one I was able to add is providers (rrd in my case), with a pattern that does show where the files are (in combination with the base directory.

**Comment by rb07** [comment]
More info I failed to see before:

The log does show that there's a problem with my configuration, I get (why is the time in GMT?):

2017/11/26 22:21:57.529510 ERROR: poller[rrdtool]: string "Envoy/Inverter3/power.rrd" does not match "\"Envoy/(?P<source>[^/]*)/(?P<metric>.*).rrd\"" pattern

No idea where the extra quotes came from.

Similar error from changing the graph definition:

2017/11/26 22:13:55.352692 WARNING: http: unable to find series metric: {Name: "Inverter3/power", Origin: "collectd", Source: "Envoy", Metric: "Inverter3/power"}

This one is missing the rrd (on the path).  But even after adding that:

2017/11/26 22:31:44.135740 WARNING: http: unable to find series metric: {Name: "Envoy/Inverter0/power", Origin: "collectd", Source: "rrd", Metric: "Envoy/Inverter0/power"}

or even:

2017/11/26 22:33:56.605592 WARNING: http: unable to find series metric: {Name: "Inverter0/power", Origin: "collectd/rrd", Source: "Envoy", Metric: "Inverter0/power"}

**Comment by vbatoufflet** [comment]
Hi @rb07,

You are right: the origins, sources and metrics come from the data found by the providers.

Did you configure the RRD provider `base_directory` using an absolute path?

**Comment by rb07** [comment]
Yes, the path in "provider definition" (if we are talking about the web interface: providers, then select the one, go into configuration, base directory) is an absolute path.

**Comment by rb07** [comment]
The extra quotes in the match pattern were put by me, sorry for the noise, still w/o the quotes (or any wildcards, or quoted dots):

`2017/11/27 16:57:36.008496 ERROR: poller[rrdtool]: string "Envoy/Inverter3/power.rrd" does not match "Envoy/(?P<source>)/(?P<metric>).rrd" pattern`

Seems to me "source", and "metric" has to be defined elsewhere, not in the graph, because those are literally correct (from the graph) and still get the "doesn't match" error.

**Comment by vbatoufflet** [comment]
Did you try with `Envoy/(?P<source>[^/]+)/(?P<metric>.+)\.rrd`?

As in the log message you pasted above `Envoy/(?P<source>)/(?P<metric>)\.rrd` misses some expressions in named groups `source` and `metric`.

**Comment by rb07** [comment]
Yes I did... but when I had it in quotes.

Trying it again **it works!** 

I also changed the name of the provider to "collectd".

Now in the graphs I'm getting completion when I enter origin/source/power.  **Success!**

Thank you!

**Comment by vbatoufflet** [comment]
You're welcome. Great to hear that it works.
