### ISSUE TITLE
Ubuntu server - RRD Missing data

### ISSUE THREAD

**Issue by gamersalpha** [facette/facette#347]
Hello there : 

i have this error 👍 

![image](https://user-images.githubusercontent.com/32466950/34342443-7619e156-e9b0-11e7-8d0c-08e16091443e.png)

this my config in facette : 

Fournisseur 👍 

![image](https://user-images.githubusercontent.com/32466950/34342447-8adc8fc6-e9b0-11e7-8069-7f9581c16727.png)

what is wrong please ?

**Comment by vbatoufflet** [comment]
Hi @gamersalpha,
Do you have specific messages in the service logs?

**Comment by gamersalpha** [comment]
i have this : 


`2017/12/26 19:16:27.294104 WARNING: http: unable to find series metric: {Name: "idle//cpu-0/cpu-idle/value/average", Origin: "idle", Source: "cpu", Metric: "/cpu-0/cpu-idle/value/average"}
2017/12/26 19:16:28.209149 WARNING: http: unable to find series metric: {Name: "memory/memory-slab_recl/value/min", Origin: "/var/lib/collectd/rrd/ubuntu/memory/", Source: "memory-free.rrd", Metric: "memory/memory-slab_recl/value/min"}
2017/12/26 19:16:28.261901 WARNING: http: unable to find series metric: {Name: "load/load/shortterm/average", Origin: "/var/lib/collectd/rrd/ubuntu/", Source: "/var/lib/collectd/rrd/ubuntu/load", Metric: "load/load/shortterm/average"}
2017/12/26 19:16:28.261974 WARNING: http: unable to find series metric: {Name: "load/load/longterm/average", Origin: "/var/lib/collectd/rrd/ubuntu/", Source: "/var/lib/collectd/rrd/ubuntu/load", Metric: "load/load/longterm/average"}
2017/12/26 19:16:28.262249 WARNING: http: unable to find series metric: {Name: "load/load/midterm/average", Origin: "/var/lib/collectd/rrd/ubuntu/", Source: "/var/lib/collectd/rrd/ubuntu/load", Metric: "load/load/midterm/average"}
2017/12/26 19:16:28.313414 WARNING: http: unable to find series metric: {Name: "average//cpu-0/cpu-idle/value/average", Origin: "average", Source: "cpu", Metric: "/cpu-0/cpu-idle/value/average"}
2017/12/26 19:16:28.313483 WARNING: http: unable to find series metric: {Name: "max//cpu-0/cpu-idle/value/max", Origin: "max", Source: "cpu", Metric: "/cpu-0/cpu-idle/value/max"}
2017/12/26 19:16:28.313703 WARNING: http: unable to find series metric: {Name: "idle//cpu-0/cpu-idle/value/average", Origin: "idle", Source: "cpu", Metric: "/cpu-0/cpu-idle/value/average"}
2017/12/26 19:16:29.228489 WARNING: http: unable to find series metric: {Name: "memory/memory-slab_recl/value/min", Origin: "/var/lib/collectd/rrd/ubuntu/memory/", Source: "memory-free.rrd", Metric: "memory/memory-slab_recl/value/min"}
2017/12/26 19:16:29.281181 WARNING: http: unable to find series metric: {Name: "load/load/shortterm/average", Origin: "/var/lib/collectd/rrd/ubuntu/", Source: "/var/lib/collectd/rrd/ubuntu/load", Metric: "load/load/shortterm/average"}
2017/12/26 19:16:29.281272 WARNING: http: unable to find series metric: {Name: "load/load/longterm/average", Origin: "/var/lib/collectd/rrd/ubuntu/", Source: "/var/lib/collectd/rrd/ubuntu/load", Metric: "load/load/longterm/average"}
2017/12/26 19:16:29.281349 WARNING: http: unable to find series metric: {Name: "load/load/midterm/average", Origin: "/var/lib/collectd/rrd/ubuntu/", Source: "/var/lib/collectd/rrd/ubuntu/load", Metric: "load/load/midterm/average"}
2017/12/26 19:16:29.332620 WARNING: http: unable to find series metric: {Name: "average//cpu-0/cpu-idle/value/average", Origin: "average", Source: "cpu", Metric: "/cpu-0/cpu-idle/value/average"}
2017/12/26 19:16:29.332681 WARNING: http: unable to find series metric: {Name: "max//cpu-0/cpu-idle/value/max", Origin: "max", Source: "cpu", Metric: "/cpu-0/cpu-idle/value/max"}
2017/12/26 19:16:29.332711 WARNING: http: unable to find series metric: {Name: "idle//cpu-0/cpu-idle/value/average", Origin: "idle", Source: "cpu", Metric: "/cpu-0/cpu-idle/value/average"}
2017/12/26 19:16:30.246177 WARNING: http: unable to find series metric: {Name: "memory/memory-slab_recl/value/min", Origin: "/var/lib/collectd/rrd/ubuntu/memory/", Source: "memory-free.rrd", Metric: "memory/memory-slab_recl/value/min"}
2017/12/26 19:16:30.302151 WARNING: http: unable to find series metric: {Name: "load/load/shortterm/average", Origin: "/var/lib/collectd/rrd/ubuntu/", Source: "/var/lib/collectd/rrd/ubuntu/load", Metric: "load/load/shortterm/average"}
2017/12/26 19:16:30.302252 WARNING: http: unable to find series metric: {Name: "load/load/longterm/average", Origin: "/var/lib/collectd/rrd/ubuntu/", Source: "/var/lib/collectd/rrd/ubuntu/load", Metric: "load/load/longterm/average"}
2017/12/26 19:16:30.302289 WARNING: http: unable to find series metric: {Name: "load/load/midterm/average", Origin: "/var/lib/collectd/rrd/ubuntu/", Source: "/var/lib/collectd/rrd/ubuntu/load", Metric: "load/load/midterm/average"}
2017/12/26 19:16:30.351204 WARNING: http: unable to find series metric: {Name: "average//cpu-0/cpu-idle/value/average", Origin: "average", Source: "cpu", Metric: "/cpu-0/cpu-idle/value/average"}
2017/12/26 19:16:30.351268 WARNING: http: unable to find series metric: {Name: "max//cpu-0/cpu-idle/value/max", Origin: "max", Source: "cpu", Metric: "/cpu-0/cpu-idle/value/max"}
2017/12/26 19:16:30.351297 WARNING: http: unable to find series metric: {Name: "idle//cpu-0/cpu-idle/value/average", Origin: "idle", Source: "cpu", Metric: "/cpu-0/cpu-idle/value/average"}
2017/12/26 19:16:31.265033 WARNING: http: unable to find series metric: {Name: "memory/memory-slab_recl/value/min", Origin: "/var/lib/collectd/rrd/ubuntu/memory/", Source: "memory-free.rrd", Metric: "memory/memory-slab_recl/value/min"}
2017/12/26 19:16:31.323318 WARNING: http: unable to find series metric: {Name: "load/load/shortterm/average", Origin: "/var/lib/collectd/rrd/ubuntu/", Source: "/var/lib/collectd/rrd/ubuntu/load", Metric: "load/load/shortterm/average"}
2017/12/26 19:16:31.323423 WARNING: http: unable to find series metric: {Name: "load/load/longterm/average", Origin: "/var/lib/collectd/rrd/ubuntu/", Source: "/var/lib/collectd/rrd/ubuntu/load", Metric: "load/load/longterm/average"}
2017/12/26 19:16:31.323463 WARNING: http: unable to find series metric: {Name: "load/load/midterm/average", Origin: "/var/lib/collectd/rrd/ubuntu/", Source: "/var/lib/collectd/rrd/ubuntu/load", Metric: "load/load/midterm/average"}
2017/12/26 19:16:31.372550 WARNING: http: unable to find series metric: {Name: "average//cpu-0/cpu-idle/value/average", Origin: "average", Source: "cpu", Metric: "/cpu-0/cpu-idle/value/average"}
2017/12/26 19:16:31.372618 WARNING: http: unable to find series metric: {Name: "max//cpu-0/cpu-idle/value/max", Origin: "max", Source: "cpu", Metric: "/cpu-0/cpu-idle/value/max"}
2017/12/26 19:16:31.372653 WARNING: http: unable to find series metric: {Name: "idle//cpu-0/cpu-idle/value/average", Origin: "idle", Source: "cpu", Metric: "/cpu-0/cpu-idle/value/average"}
2017/12/26 19:16:32.283640 WARNING: http: unable to find series metric: {Name: "memory/memory-slab_recl/value/min", Origin: "/var/lib/collectd/rrd/ubuntu/memory/", Source: "memory-free.rrd", Metric: "memory/memory-slab_recl/value/min"}
2017/12/26 19:16:32.340838 WARNING: http: unable to find series metric: {Name: "load/load/shortterm/average", Origin: "/var/lib/collectd/rrd/ubuntu/", Source: "/var/lib/collectd/rrd/ubuntu/load", Metric: "load/load/shortterm/average"}
2017/12/26 19:16:32.340900 WARNING: http: unable to find series metric: {Name: "load/load/longterm/average", Origin: "/var/lib/collectd/rrd/ubuntu/", Source: "/var/lib/collectd/rrd/ubuntu/load", Metric: "load/load/longterm/average"}
2017/12/26 19:16:32.340931 WARNING: http: unable to find series metric: {Name: "load/load/midterm/average", Origin: "/var/lib/collectd/rrd/ubuntu/", Source: "/var/lib/collectd/rrd/ubuntu/load", Metric: "load/load/midterm/average"}
2017/12/26 19:16:32.390511 WARNING: http: unable to find series metric: {Name: "average//cpu-0/cpu-idle/value/average", Origin: "average", Source: "cpu", Metric: "/cpu-0/cpu-idle/value/average"}
2017/12/26 19:16:32.390574 WARNING: http: unable to find series metric: {Name: "max//cpu-0/cpu-idle/value/max", Origin: "max", Source: "cpu", Metric: "/cpu-0/cpu-idle/value/max"}
2017/12/26 19:16:32.390720 WARNING: http: unable to find series metric: {Name: "idle//cpu-0/cpu-idle/value/average", Origin: "idle", Source: "cpu", Metric: "/cpu-0/cpu-idle/value/average"}

`

**Comment by vbatoufflet** [comment]
Do you have messages as well when you start the provider? Do you see metrics in the “Metrics” section of the administration pane?

**Comment by smortex** [comment]
FWIW, I usually see that when I restart facette: the first few requests fail that way, and after a few moments, the actual data comes back to life.

**Comment by vbatoufflet** [comment]
I'm closing this. Please reopen if need be.
