### ISSUE TITLE
Inconsitent rendering when data is missing

### ISSUE THREAD

**Issue by smortex** [facette/facette#348]
Hello,

I have seen this a few times but never took time to report it, so to ovoid this to be lost and maybe see that fixed some days, here are the details.

When data is missing from collectd, it seems that facette still draws something on graphs.  The resulting graph is really surprising, for example, here is the "uptime" of a node that crashed at 09:00, was rebooted at 13:30, and rebooted another time at ~16:00.

![Uptime](https://screenshots.firefoxusercontent.com/images/66f5201e-85ba-4a8f-9360-65341628c48f.png)

As you can imagine, uptime is supposed to be monotonically increasing by 1 each second.  I would therefore expect the graph to be only composed of increasing lines with a constant slope.  It looks like each time data is missing (i.e. the node is down and does not send data to collectd) we have some kind of 'N' vertically reversed on the graph:

* When data starts to be missing, the value drops
* When data stops to be missing, the value jumps to that last known-good value (or nearby).  A stroke is drawn between the previous (incorrect) point and this (incorrect) point;
* Further valid data is received and a stroke is drawn between the second incorrect point and the actual data.

The situation is similar on all graphs:

![Load average](https://screenshots.firefoxusercontent.com/images/22ce83ba-ce71-4bf3-b3e5-ac98a5d99928.png)
![CPU usage](https://screenshots.firefoxusercontent.com/images/cbc0c654-8d83-4b5e-b3cf-8071151c0087.png)
![Memory usage](https://screenshots.firefoxusercontent.com/images/749a9688-c572-419c-a1b6-84908534cec5.png)

As you can see on the last graph, sometimes the 'N' is not reversed.  A quick guess would be that facette attempts to draw a line from the last value before absence of data to the one after data gets available again, but values are reversed?

FWIW, I feel like no stroke when there is no data would be perfect.

**Comment by vbatoufflet** [comment]
Hi @smortex,

Is “Interpolate missing points” checked on the series present on the graph?

<img width="356" alt="screen shot 2018-01-08 at 08 25 13" src="https://user-images.githubusercontent.com/598433/34661983-a0b5e53e-f44d-11e7-8eed-fc05bf53c980.png">

This option is checked by default. If you unchecked it, does it have the intended behavior?

**Comment by smortex** [comment]
Damned!  This option was one click away (I looked at the graphs level, not series level)…

Thanks :+1: !

I'll have to find a way to change all settings without clicking on all my series so that it fits my needs (hints are welcome, like managing facette without the admin GUI :wink: ).

**Comment by vbatoufflet** [comment]
You can retrieve the groups data for a graph using:
```
curl -s localhost:12003/api/v1/library/graphs/eccd09c3-aaa9-592b-ad55-3d92b4acf119?fields=groups
{
  "groups": [
    {
      "name": "",
      "operator": 0,
      "consolidate": 1,
      "series": [
        {
          "name": "shortterm",
          "origin": "{{ .origin }}",
          "source": "{{ .source }}",
          "metric": "load.shortterm",
          "options": {
            "color": "#fff726"
          }
        }
      ],
      "options": {
        "interpolate": true
      }
      …
}
```

After setting the `interpolate` option to `false`, you can apply the modification with a `PATCH` query:
```
curl -s -XPATCH -H 'Content-Type: application/json' localhost:12003/api/v1/library/graphs/eccd09c3-aaa9-592b-ad55-3d92b4acf119 -d '<your-json-data>'

See https://docs.facette.io/latest/api/library/#partially-update-a-library-item.

But it will need a loop to retrieve all graphs ids and there is no easy way to achieve this, sorry.

**Comment by vbatoufflet** [comment]
I'll try to think for a better solution for a future release (see #349).

**Comment by smortex** [comment]
Well, in fact I was thinking about ways to automate graphs creations and life-cycle.  It's not very mature in my head, but as an IT automation user (Puppet), I like the idea of describing my configurations in manifests file and apply these configurations to hosts.  For now, my facette configuration only installs facette and manage the service, so all the configuration must be done by hand.  Hopefully, you only do this once :smile: 

BTW, I ended up writing a small script to set this *interpolate* parameter to *false* for all my series directly in the DB.  I guess this may break things. but so far it seems to be exactly what I wanted.  Thank you for your advices!

In case it might help somebody with similar requirements:
```ruby
#!/usr/bin/env ruby

require 'json'
require 'sqlite3'

db = SQLite3::Database.new(ARGV[0])

db.execute('SELECT id FROM graphs').inject(:+).each do |graph_id|
  groups_json = db.execute('SELECT groups FROM graphs WHERE id = ?', graph_id)[0][0]

  begin
    groups = JSON.parse(groups_json)

    groups.each do |group|
      group['options'] ||= {}
      group['options']['interpolate'] = false
    end

    db.execute('UPDATE graphs SET groups = ? WHERE id = ?', groups.to_json, graph_id)
  rescue JSON::ParserError
    # Ignore this entry
  end
end
```

**Comment by vbatoufflet** [comment]
Ahah my bad 😅

At work, I am using a custom Salt module (along with a basic Python binding) handling this for me based on hosts registered in Salt's mine.

But there is nothing quite “official” yet 🙂

Thanks for the code snippet though.
