### ISSUE TITLE
Upgrade import documentation?

### ISSUE THREAD

**Issue by FacetteUser** [facette/facette#351]
I'm trying to upgrade from a 0.3.0 install to the 0.4.0 release. After upgrading everything it appears that my entire library is gone and not imported. How does one do this? I tried to use `facettectl library dump -o dump.tgz` running a pre update snapshot, but 0.3.0 doesn't support this feature. Seems absolutely unimaginable that I would have recreate my entire setup with hundreds of graphs, templates, and collections upgrading to 0.4.0, I must be missing something obvious. I looked all over in the documentation, past issues, etc, nothing.

**Comment by vbatoufflet** [comment]
In the effort of making Facette 0.4 the first official production-ready release we had to rewrite the entire back-end for stability and performance purposes.

The said rewrite made the previous file storage incompatible and as you pointed it out, the previous version of Facette didn't had the dump feature.

There is a Gist available at [this address](https://gist.github.com/vbatoufflet/885ade1d1b434bb8c6861d3c7cc31650) to generate such dump. But currently there is still missing a proper handling of metric/source groups restoration. I'll try to fix that as soon as possible.

We can surely add a note somewhere regarding that incompatibility though.

**Comment by FacetteUser** [comment]
That gist, even if it's missing metric/source group, is definitely what I was looking for, merci beaucoup!

Would be great if something like this was included in facettectl to ease migration, maybe migration could be detected automatically on new installs and the user prompted in the front-end to do this automagically?

I'm closing the ticket as you've resolved my issue for the most part.
