### ISSUE TITLE
upload generated source tarball to assets on releases

### ISSUE THREAD

**Issue by landryb** [facette/facette#356]
It would be nice to upload source tarballs for packagers on the release assets, as of now unfortunately the autogenerated ones provided by github (the 'source code' links as https://github.com/facette/facette/archive/0.4.0.tar.gz) arent guaranteed stable by github, they're generated on the fly sometimes with different toolchains producing different results and cached randomly, so one might get different tarballs/checksums when integrating with a packaging system.

**Comment by vbatoufflet** [comment]
Hi @landryb,

I surely can add this build step in the release process.

**Comment by vbatoufflet** [comment]
The future 0.5.0 release will come with a generated source tarball (can now be generated using `make dist-source` in the source tree).
