### ISSUE TITLE
sub-collections not shown when using collections/alias

### ISSUE THREAD

**Issue by arlt** [facette/facette#358]
Example folder structure of my rrds (compact version):

```
`-- host.domain.tld
    |-- load
    |   `-- load.rrd
    |-- memory
    |   |-- memory-buffered.rrd
    |   |-- memory-cached.rrd
    |   |-- memory-free.rrd
    |   |-- memory-slab_recl.rrd
    |   |-- memory-slab_unrecl.rrd
    |   `-- memory-used.rrd
    `-- processes
        |-- fork_rate.rrd
        |-- ps_state-blocked.rrd
        |-- ps_state-paging.rrd
        |-- ps_state-running.rrd
        |-- ps_state-sleeping.rrd
        |-- ps_state-stopped.rrd
        `-- ps_state-zombies.rrd
...
```

I create the facette config this way from these rrds (you can see the script the end of #266):

- create all graphs (all rrds)
- create level 1 collection for each fqdn
  - "alias" is set to the fqdn
  - with entries: two graphs (load+memory-free)
- create level 2 collection for each rrd-folder (e.g. load memory)
  - "parent" is set to the id (from "Location:" output) of created level 1 collection (fqdn)
  - with entries: all rrds from the folder as graph

If i browse my facette, all is fine:
- collection level 1 (fqdns) - if i click on the fqdn collection:
  - both graphs are shown
  - level 2 collection can be seen

"Screenshot" url `/browse/`:

```
Browse
  host.domain.tdl
  |--  load
  |--  memory
  `--  processes
```

"Screenshot" url `/collections/0a815100-c5b2-ba23-6d6d-e43bd0caf4c8`:

```
Browse
<- Go to home page
  load
  memory
  processes
```

But if i change the url from `collections/<id>` to `collections/<alias>` the two graphs can be seen but the level 2 collection at the left side is missing.

"Screenshot" url `/collections/host.domain.tld`:

```
Browse
<- Go to home page
```

I am not sure if this is a self-made problem or an issue in facette.

**Comment by vbatoufflet** [comment]
Hi @arlt,

You should have the same behavior using either an ID or an alias. I'll take a look and try to reproduce it.

**Comment by falzm** [comment]
@arlt thank you for reporting this bug, this problem should now be fixed. We'll release a new version including this patch ASAP.

**Comment by arlt** [comment]
@vbatoufflet @falzm I am sorry, but i get the same result as before.
Tested here with Ubuntu 16.04 and the new 0.4.1-1 deb-file - recreated all with the script., restarted apache and used the browser in private mode.
Should i open a new issue or can you reopen it, please?

**Comment by falzm** [comment]
Sorry to ask, but in addition to Apache have you actually restarted the Facette process itself? Can you please give us the output of the following command?

```
curl http://<your Facette instance hostname or IP address>/api/v1/
```

**Comment by arlt** [comment]
I was not able to reopen this issue (you closed it).

> you can re-open your own issues *if you closed them yourself

https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

But: Sorry you are right. I forgot to restart the collectd process argl :-(

Thank you very much!

**Comment by falzm** [comment]
No worries, thanks again for bringing this issue to our attention :)
