### ISSUE TITLE
Building a .deb for ARMv7

### ISSUE THREAD

**Issue by mthmulders** [facette/facette#366]
I would like to run Facette on my Raspberry Pi 3, which has an ARMv7 processor. Since there's no package available for download, I tried to build it myself. That succeeded without problems. Now, I would prefer to install it using dpkg, to have the right folder structure as well as having Facette start at boot.

At first, I did `dpkg-deb --build .` which failed because there is no `DEBIAN/` subdirectory. So I added a symlink (`DEBIAN` -> `debian`) and tried again.

Now it fails with

    dpkg-deb: error: parsing file './DEBIAN/control' near line 11:
     missing package name

And I have no idea how to fix this. What is the command that the Facette team uses to build the Debian packages?

**Comment by vbatoufflet** [comment]
Hi @mthmulders,

The build of Debian packages are handled through Docker build environments available [here](https://github.com/facette/buildenv).

If you take a look at https://github.com/facette/buildenv/blob/master/docker/Dockerfile.stretch-amd64 you'll have a good overview of build prerequisites.

Having the environment set up, you may simply run `make dist-deb` when building from master to generate a .deb file that will be available in the `dist/` folder upon success.

**Comment by vbatoufflet** [comment]
Sure, if provided with a working ARMv7 Docker build environment we can add it to the releases.

**Comment by mthmulders** [comment]
Will see what I can do. Currently blocked by facette/buildenv#1.

**Comment by mthmulders** [comment]
See facette/buildenv#2.

**Comment by vbatoufflet** [comment]
Future releases will ship this architecture.
