### ISSUE TITLE
308 Permanent Redirect on /api/v1

### ISSUE THREAD

**Issue by rshade** [facette/facette#368]
I am going thru the initial setup and trying the auto script in #266 but my api is returning a 308. I tried just the base url and it errors also. read_only is set to false, and base_path is unset. 
I did change the url from localhost to a 192 ip. Any ideas on how to fix this?

**Comment by rshade** [comment]
Version: 0.5.0rc1

**Comment by rshade** [comment]
`2019/02/20 21:06:40.115507 INFO: http: started
2019/02/20 21:06:40.119613 INFO: http: listening on "192.168.11.106:12003"
2019/02/20 21:06:40.121179 INFO: poller: started
2019/02/20 21:06:42.532480 DEBUG: http: received "GET /api/v1 HTTP/1.1" from 192.168.11.106:55756, returned: 308
2019/02/20 21:07:02.636144 DEBUG: http: received "GET /api/v1 HTTP/1.1" from 192.168.11.106:55758, returned: 405
2019/02/20 21:07:07.235107 DEBUG: http: received "GET /api/v1 HTTP/1.1" from 192.168.11.106:55760, returned: 405
2019/02/20 21:07:17.235786 DEBUG: http: received "POST /api/v1/providers HTTP/1.1" from 192.168.11.106:55762, returned: 308
`

**Comment by vbatoufflet** [comment]
Hi @rshade,

The API endpoints did change a bit since the script was written. The API is returning 308 for some endpoints when not called with the trailing `/`.

**Comment by vbatoufflet** [comment]
I'll close the issue. Please reopen if needed.
