### ISSUE TITLE
facette difficult to setup

### ISSUE THREAD

**Issue by vojtechkral** [facette/facette#369]
Hi,
  I had a hard time setting up facette 0.4 on a build machine today. I found next to no documentation on how to hook facette up with data providers - collectd in my case. After installation, facette displayed an empty webpage. Poking around in the admin panel revealed a lot of options and dialogs but no indication whatsoever as to how to go about the configuration. After some googling I found [this old Arch package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=facette), where they seem to be installing json config files, which the new version doesn't seem to use anymore. I found the old examples [in the 0.3 branch](https://github.com/facette/facette/blob/0.3/docs/examples/providers/collectd.json) and basically copy-pasted those into the admin panel GUI.

That was the only way I could get facette to do anything. Now that it works, I'm quite satisfied, it looks very nice indeed, but it feels like the setup should've been easier. Had I missed something important in the docs or elsewhere? Maybe I screwed up somehow at some point? Could the examples be restored and, for example, made part of the admin panel GUI?

Thanks!

**Comment by vbatoufflet** [comment]
Hi @vojtechkral,

Sadly, you didn't miss anything ;)

Today, the projects lacks some documentation about the web UI usage. It's definitively something that we plan to improve in the future.

I just opened the #370 to follow up on this.

**Comment by kousu** [comment]
I don't really want a UI wizard. I just want some way to use facette. 

@vojtechkral can you share where you pasted the collectd config file? I can't figure it out. I don't have anywhere I could paste anything in the facette UI.

**Comment by vbatoufflet** [comment]
Hi @kousu,

You can't paste the configuration as is.

That said, let's say you want to configure a new “rrd” provider.

In the _Adminitration Panel > System > Providers_, click on _Create new provider_ (see ①):

![facette-howto-rrd_img1](https://user-images.githubusercontent.com/598433/57278330-7ae1a100-70a6-11e9-968e-445574e53e07.png)

Set a name for your new provider, like “rrd” or “my-first-provider” (see ②) and chose “rrd” as connector type then click on _Configure_ (see ③):

![facette-howto-rrd_img2](https://user-images.githubusercontent.com/598433/57278344-82a14580-70a6-11e9-96bf-3291648957cb.png)

For the sake of this example, let's assume rrd files are located in `/var/lib/collectd/rrd`.

Specify you desired path as connector's base directory (see ④) and define a match pattern that will be used to map found files to sources and metrics in Facette (see ⑤).

In this example, using `(?P<source>[^/]+)/(?P<metric>.+).rrd` will map (relative to base directory) `host1.example.net/cpu/percent-user.rrd` to:

* source: `host1.example.net`
* metric: `cpu/percent-user`

![facette-howto-rrd_img3](https://user-images.githubusercontent.com/598433/57278348-85039f80-70a6-11e9-8d17-bf33df4c2878.png)

Once done, click _Ok_ then _Save provider_ (see ⑥).

![facette-howto-rrd_img4](https://user-images.githubusercontent.com/598433/57278360-892fbd00-70a6-11e9-984e-d82a86c75876.png)

You should now have sources and metrics in _Administration Panel > Catalog_.

Let me know if some of those explications are not clear of if something is missing.

**Comment by kousu** [comment]
Ah I see! My problem was I was still on 0.3.0 because of my package mirror, so I didn't have any of those options and also I didn't have `collectd-rrdtool` installed so facette had no sources to load.

Those screenshots will help for 0.4.0+ :)

**Comment by vbatoufflet** [comment]
I'll close this issue for now. Don't hesitate to reopen if need be.
