### ISSUE TITLE
no Graph after Unfold

### ISSUE THREAD

**Issue by 532910** [facette/facette#371]
Before:
![image](https://user-images.githubusercontent.com/14617699/61703781-01735980-ad4b-11e9-87a8-a0cfa97ca943.png)

Folded:
![image](https://user-images.githubusercontent.com/14617699/61703791-06d0a400-ad4b-11e9-94e1-fc6970c1eade.png)

After:
![image](https://user-images.githubusercontent.com/14617699/61703809-0f28df00-ad4b-11e9-99f4-dd3556af67a6.png)

Refresh graph doesn't help.

**Comment by vbatoufflet** [comment]
Hi @532910,

Thanks for reporting this! Indeed, I do reproduce the issue. I'll come up with a fix for this.

**Comment by 532910** [comment]
I confirm that 0.5 works fine for me
