### ISSUE TITLE
graph scale issues

### ISSUE THREAD

**Issue by 532910** [facette/facette#373]
1. Default Y-Axis  auto min max values scales graph from 0:
![image](https://user-images.githubusercontent.com/14617699/61709295-8e241480-ad57-11e9-928c-fc84949682ca.png)

2. Setting Y-Axis values to specific values (500, 1200) just draws red line:
![image](https://user-images.githubusercontent.com/14617699/61709397-d3e0dd00-ad57-11e9-855d-99d6d297b0bf.png)

**Comment by vbatoufflet** [comment]
That's definitely a bug, the Y-axis should start at the minimum value (500 here). Thanks for reporting this.

**Comment by 532910** [comment]
I can't say it's fixed, and I see two issues here:

1. When `Minimum value` is specified the red line is shown:
![image](https://user-images.githubusercontent.com/14617699/62432218-33b38c80-b737-11e9-8583-918d491fc61a.png)

2. When `Maximum value` is `auto` then it will be graph's maximum on the shown interval. This is correct behaviour, but I'd like to see graph's maximum + 5% for example, just for nice look.
But when `Minimum value` is `auto` then it will be zero! And this is the issue, as it should be calculated the same as for `auto` `Maximum value`.
![image](https://user-images.githubusercontent.com/14617699/62432401-2cd94980-b738-11e9-82e8-dc4ce70e492a.png)

**Comment by vbatoufflet** [comment]
Hi @532910,

1. Red dashed lines are shown when the minimum/maximum value for the data points retrieved on the time interval goes below/above graph's configured boundaries. It denotes that series are kinda “cropped”.

2. I guess having a way to have some kind of +%5 (or any other value) tolerance could be implemented, I'll have to think about a proper way to do that. The fact that the Y-Axis always starts at zero is hardcoded indeed, it was a choice I made with the firsts version of Facette, it could be made configurable too I guess.

**Comment by 532910** [comment]
1. I agree that some signs should be shown when the graph is really cropped. But it's not cropped on the screenshot above.

Should I open separate issues for 1 and 2 ?

**Comment by vbatoufflet** [comment]
Yes, it would be great. Thanks!
