### ISSUE TITLE
left menu & mobile version

### ISSUE THREAD

**Issue by 532910** [facette/facette#375]
The left menu (hamburger button) collapses back just momens after pressing it in mobile version.
Frefox mobile / chromium mobile / firefox desktop with "responsive design mode" (Ctrl-Shift-M, Web/Developer -> phone icon)

**Comment by vbatoufflet** [comment]
Hi @532910,

Thanks again for reporting this. I'll take a look at it.

**Comment by 532910** [comment]
0.5.1 works fine!
