### ISSUE TITLE
base_path/api/v1 doesn't work

### ISSUE THREAD

**Issue by clarfon** [facette/facette#384]
Right now, `base_path` applies to the UI, but doesn't actually accept API connections. If I proxy facette to `localhost:8080/facette`, the UI will try to access `localhost:8080/facette/api/v1` and this will simply return the HTML UI instead of the API endpoint.

**Comment by vbatoufflet** [comment]
Hi @clarfon,

Thanks for pointing this out! This is now fixed.

I'll will ship the fix in the 0.5.1 release.
