### ISSUE TITLE
Rename Series Names

### ISSUE THREAD

**Issue by sstallion** [facette/facette#388]
While working on setting up facette for my local network, I haven't been able to find a way to rename the series names to more meaningful values similar to play.facette.io (screenshot attached). Is it possible to do this through the UI? The below example visualizes load averages and I can't seem to figure out a way to relabel.

![example](https://user-images.githubusercontent.com/5983112/68739805-5a435800-05af-11ea-919c-3d89b2559a80.png)

**Comment by vbatoufflet** [comment]
Hi @sstallion,

When editing your graph, in the series list you can click on the cog icon near the series you want to edit:
![Screenshot_2019-11-13 New graph – Administration panel – Facette](https://user-images.githubusercontent.com/598433/68741246-6b12be80-05ed-11ea-9cd5-6871a40e71ec.png)

Once done you'll be able to set its name:
![Screenshot_2019-11-13 New graph – Administration panel – Facette(1)](https://user-images.githubusercontent.com/598433/68741275-7c5bcb00-05ed-11ea-96e1-4e2c29e138ba.png)

**Comment by sstallion** [comment]
Perfect. Thanks!
