### ISSUE TITLE
Move collection graph optional settings to graph edit/create page

### ISSUE THREAD

**Issue by falzm** [facette/facette#75]
We should move optional graph settings (i.e. constants, samples, percentiles) to the same place as other graph settings, because in the case we access a graph via search results we cannot set percentiles to a graph without including it in a collection (then setting the percentiles within the collection).

Besides, it makes more sense to set all the graph settings in the same place.

m.

**Comment by vbatoufflet** [comment]
Shipped in [0.4-alpha](https://github.com/facette/facette/tree/0.4-alpha).
