### ISSUE TITLE
CSV connector

### ISSUE THREAD

**Issue by falzm** [facette/facette#94]
It might be nice to be able to extract metrics from CSV-formatted files:

 * walk a directory tree of files and map the file paths to *sources* (content of files would be *metrics*)
 * provide a customizable time format parsing (using Go's standard *time* package `Parse()` function?) and field selection settings

**Comment by bbczeuz** [comment]
collectd has a csv plugin. Could help, but I've never tried it myself.

**Comment by falzm** [comment]
Yes it could help to generate CSV files for testing, but ideally this connector should be able to "query" datapoints from any CSV-formatted file.
